<?php

use Bluz\Proxy\Logger;

?>

<?php if (getenv('BLUZ_DEBUG') && $info = Logger::get('info')) : ?>
    <nav id="debug" class="navbar collapse show navbar-light shadow bg-light fixed-bottom">
        <div class="container-fluid" style="max-height: 50vh">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#log"
                    aria-controls="debug" aria-expanded="false" aria-label="Toggle debug log">
                <i class="bi bi-exclamation-octagon"></i>
            </button>
            <div class="navbar-brand"><?=array_key_last($info)?></div>
            <button type="button" class="btn-close" aria-label="Close" data-bs-toggle="collapse" data-bs-target="#debug"></button>
            <div id="log" class="collapse navbar-collapse" style="max-height: 40vh; overflow: scroll">
                <table class="table table-striped table-hover fs-6">
                    <thead>
                    <tr>
                        <th scope="col" width="280px">Timer</th>
                        <th scope="col">Event</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($info as $key => $value) : ?>
                        <tr>
                            <td scope="row" align="left"><code><?=$key?></code></td>
                            <td align="left"><?=$value?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </nav>

<?php endif; ?>

</body>
</html>
