<?php
/** @var \Bluz\Layout\Layout $this */

use Bluz\Proxy\Layout;
use Bluz\Proxy\Messages;

?>
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?= Layout::title() ?></title>
    <base href="<?= $this->baseUrl() ?>"/>
    <link rel="profile" href="http://gmpg.org/xfn/11"/>

    <link rel="stylesheet" href="<?= $this->baseUrl('vendor/bootstrap/css/bootstrap.css') ?>"/>
    <link rel="stylesheet" href="<?= $this->baseUrl('vendor/bootstrap/css/bootstrap-icons.css') ?>"/>
    <link rel="stylesheet" href="<?= $this->baseUrl('css/styles.css') ?>"/>
    <link rel="stylesheet" href="<?= $this->baseUrl('css/print.css') ?>" media="print"/>

    <link rel="shortcut icon" sizes="any" href="<?= $this->baseUrl('img/favicon.ico') ?>"/>
    <link rel="icon" href="<?= $this->baseUrl('img/icon.svg') ?>" type="image/svg+xml">
    <link rel="apple-touch-icon" sizes="180x180" href="<?= $this->baseUrl('img/apple-touch-icon.png') ?>"/>
    <link rel="manifest" href="<?= $this->baseUrl('img/manifest.json') ?>"/>
    <meta name="msapplication-config" content="<?= $this->baseUrl('img/browserconfig.xml') ?>"/>
    <meta name="theme-color" content="#ffffff"/>

    <script src="<?= $this->baseUrl('js/bluz.js') ?>" type="module"></script>

    <?= Layout::headScript(); ?>
    <?= Layout::headStyle(); ?>
    <?= Layout::link(); ?>
    <?= Layout::meta(); ?>
</head>
<body data-spy="scroll" data-bluz-module="<?= $this->module() ?>" data-bluz-controller="<?= $this->controller() ?>">
<?php
if (Messages::count()):
    // JS not allow read headers of current request, only for XMLHTTPRequests :(
    ?>
    <script type="module">
        import {notify} from '/js/bluz.notify.js';
        notify.set(<?=json_encode(Messages::popAll())?>);
    </script>
<?php
endif; ?>
