<div class="page-header">
    <h1>Cache management</h1>
</div>
<div class="subnav">
    <ul class="nav nav-pills">
        <li class="bluz-tooltip" data-placement="bottom" data-original-title="Cache Servers Stats"><?=$this->ahref('Statistics', ['cache', 'stats'])?></li>
        <li class="bluz-tooltip" data-placement="bottom" data-original-title="Clean ACL and Route Maps"><?=$this->ahref('<i class="icon-fire"></i> Clean', ['cache', 'clean'], ['class'=>'confirm ajax'])?></li>
        <li class="bluz-tooltip" data-placement="bottom" data-original-title="Flash all servers"><?=$this->ahref('<i class="icon-fire"></i> Flush', ['cache', 'flush'], ['class'=>'confirm ajax'])?></li>
    </ul>
</div>
<?php if (isset($servers) && sizeof($servers)): ?>
<hr/>
<div>
    <table class="table-bordered table-condensed">
        <tr>
            <th class="span3">Server</th>
            <th class="span2 textcenter">Weight</th>
        </tr>
        <?php foreach ($servers as $stat):?>
        <tr>
            <td><?=$stat['host']?>:<?=$stat['port']?></td>
            <td class="textcenter"><?=isset($stat['weight'])?$stat['weight']:''?></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>
<?php endif; ?>