<div class="page-header">
    <h1>Cache management</h1>
</div>
<div class="subnav">
    <ul class="nav nav-pills">
        <li><?=$this->ahref('Statistics', ['cache', 'stats'])?></li>
        <li><?=$this->ahref('<i class="icon-fire"></i> Flush', ['cache', 'flush'], ['class'=>'confirm ajax'])?></li>
    </ul>
</div>
<?php if (sizeof($servers)): ?>
<hr/>
<div>
    <table class="table-bordered table-condensed">
        <tr>
            <th class="span3">Server</th>
            <th class="span2 textcenter">Weight</th>
        </tr>
        <?php foreach ($servers as $stat):?>
        <tr>
            <td><?=$stat['host']?>:<?=$stat['port']?></td>
            <td class="textcenter"><?=$stat['weight']?></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>
<?php endif; ?>