<div class="page-header">
    <h1><?=__('Cache statistics')?></h1>
</div>
<div>
    <?php if ($adapter instanceof \Bluz\Cache\Adapter\Memcached) : ?>
        <?php foreach ($adapter->getHandler()->getStats() as $server => $stat): ksort($stat)?>
        <table class="table table-hover table-bordered table-condensed">
            <caption><?=$server?></caption>
            <?php foreach($stat as $key => $value): ?>
            <tr>
                <th><?=$key?></th>
                <td class="text-right"><?=$value?></td>
            </tr>
            <?php endforeach; ?>
        </table>
        <?php endforeach; ?>
    <?php elseif ($adapter instanceof \Bluz\Cache\Adapter\Redis): ?>
        <table class="table table-hover table-bordered table-condensed">
            <?php foreach($adapter->getHandler()->info() as $key => $value): ?>
                <tr>
                    <th><?=$key?></th>
                    <td class="text-right"><?=$value?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php elseif ($adapter instanceof \Bluz\Cache\Adapter\Apc): ?>
        <table class="table table-hover table-bordered table-condensed">
            <?php foreach(apc_cache_info() as $key => $value): ?>
                <tr>
                    <th><?=$key?></th>
                    <td class="text-right">
                        <?php
                        if (is_array($value)) :
                            echo '"'.sizeof($value).'" elements in array';
                        else:
                            echo $value;
                        endif;
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php elseif ($adapter instanceof \Bluz\Cache\Adapter\FileBase): ?>
        <?=__('Statistics is not available for current cache adapter')?>
    <?php endif; ?>
</div>