<div class="page-header">
    <h1>Cache statistics</h1>
</div>
<div>
    <table class="table-bordered table-condensed">
    <?php foreach ($servers as $server => $stat): ksort($stat)?>
        <tr>
            <th colspan="2"><?=$server?></th>
        </tr>
        <?php foreach($stat as $key => $value): ?>
        <tr>
            <th class="span3"><?=$key?></th>
            <td class="span2 textright"><?=$value?></td>
        </tr>
        <?php endforeach; ?>
    <?php endforeach; ?>
    </table>
</div>