checks:
  php:
    code_rating: true
    deprecated_code_usage: true
    duplication: true
    no_short_open_tag: true
build:
  cache:
    directories:
      - vendor        # Cache for already installed composer package -> speed up composer install
      - bin           # As vendor directory is cached, bin directory must be also cached (as some dependency will not installed if they are already present and so, related binary will not be linked)
      - ~/.composer   # Composer home directory (avoid fetching already fetched packages)
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
  dependencies:
    override:
      - COMPOSER_ROOT_VERSION=dev-master
filter:
  paths: [application]
  excluded_paths: [bin, data, docs, docker, public, tests, vendor]
  dependency_paths: [vendor]
tools:
  external_code_coverage: false
  php_analyzer: true
  php_code_sniffer:
    config:
      standard: PSR12
  php_cpd:
    enabled: true
    excluded_dirs: [bin, data, docs, docker, public, tests, vendor]
  php_loc:
    enabled: true
    excluded_dirs: [bin, data, docs, docker, public, tests, vendor]
  php_mess_detector: true
  php_pdepend: true
  sensiolabs_security_checker: true
