<div class="navbar">
    <a href="<?=$this->url('acl', 'roles')?>" class="btn btn-primary dialog" data-ajax-method="get">Add New Role</a>
    <a href="<?=$this->url('acl', 'users')?>" class="btn">Users Roles</a>

    <?//=$this->ahref('Direct Rules Management', ['acl', 'direct'], ['class' => 'btn']);?>
</div>
<form action="<?=$this->url('acl', 'save')?>" method="POST">
<table class="table table-bordered table-condensed ">
    <thead>
        <tr>
            <th width="180px">Privilege/Role</th>
            <?php foreach ($roles as $role) : ?>
            <th width="180px">
                <?=$role->name?>
                <?php if (!$role->isBasic()) : ?>
                <a href="<?=$this->url('acl', 'roles', ['data' => ['id' => $role->id]]);?>" class="confirm btn btn-mini btn-danger ajax right" data-ajax-method="delete"><i class="icon-remove icon-white"></i></a>
                <span class="right">&nbsp;</span>
                <a href="<?=$this->url('acl', 'roles', ['data' => ['id' => $role->id]]);?>" class="btn btn-mini dialog right" data-ajax-method="get" title="Edit"><i class="icon-edit"></i></a>
                <?php endif; ?>
            </th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($set as $module => $modulePrivileges) : ?>
        <tr>
            <th colspan="<?=sizeof($roles) + 1?>"><?=ucfirst($module)?></th>
        </tr>
    <?php foreach ($modulePrivileges as $privilege) : ?>
        <tr>
            <td><?=$privilege?></td>
            <?php foreach ($roles as $role) : ?>
            <td>
                <input type="checkbox" name="acl[<?=$role->id?>][<?=$module?>][<?=$privilege?>]" value="1"
                <?=((isset($privileges[$role->id]) && isset($privileges[$role->id][$module]) && in_array($privilege, $privileges[$role->id][$module]))?"checked":"")?> /></td>
            <?php endforeach; ?>
        </tr>
    <?php endforeach; ?>
    <?php endforeach; ?>
    </tbody>
</table>
    <input type="submit" value="Save" class="btn btn-primary"/>
</form>