<?php $uid = uniqid('form_', false); ?>
<form id="<?= $uid ?>" action="<?= $this->url('acl', 'roles') ?>" class="form-horizontal" data-ajax method="<?= $method ?>">
  <input type="hidden" name="id" value="<?= $row->id ?>"/>
  <div class="modal-header">
    <h4 class="modal-title">
        <?= (strtoupper($method) === 'POST' ? __('Create role') : __('Edit role')) ?>
    </h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="<?=__('Close')?>">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="form-group row">
      <label class="col-form-label col-lg-2" for="name"><?= __('Name') ?></label>
      <div class="col-lg-10">
        <input type="text" class="form-control" id="name" name="name" value="<?= ($row->name) ?>"
               pattern="[a-zA-Z0-9-_ ]+" required/>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary"><?= __('Save') ?></button>
    <a href="#" class="btn btn-light" data-dismiss="modal"><?= __('Close') ?></a>
  </div>
</form>
<?php
// need for plain request
if (isset($errors)) :
    echo $this->partial('crud/errors.phtml', ['uid' => $uid, 'errors' => $errors]);
endif;
?>
