<?php $uid = uniqid('form_'); ?>

<form id="<?=$uid?>" action="<?=$this->url('acl', 'roles')?>" class="form-horizontal ajax" method="<?=$method?>">
    <input type="hidden" name="data[id]" value="<?=$row->id?>"/>
    <div class="modal">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h3>
                <?=($method=='post'?'Create Role':'Edit Role')?>
            </h3>
        </div>
        <div class="modal-body">
            <div class="control-group">
                <label class="control-label" for="name"><?=$this->__('Name')?></label>
                <div class="controls">
                    <input type="text" class="input-xlarge" id="name" name="data[name]" value="<?=($row->name)?>" />
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary"><?=$this->__('Save')?></button>
            <a href="#" class="btn" data-dismiss="modal"><?=$this->__('Close')?></a>
        </div>
    </div>

</form>
