<?php $this->script("
    function resourceTabs() {
        $('.tabs').tabs();
    }
")?>
<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th width="180px"><?=__('User')?></th>
            <th><?=__('Role')?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $user):?>
        <tr>
            <td>
                <?=
                    $this->ahref($user->login, ['acl', 'edit-user', ['id' => $user->id]], ['class'=>"dialog", 'data-ajax-method'=>'get'])
                        ?: $user->login
                ?>
            </td>
            <td><?=$user->roles?>
                <?//=$this->ahref($user->getRole(), ['acl', 'edit-user', ['id' => $user->getId()]], ['class' => 'dialog']) ?: $user->getRole()?></td>
            <td></td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>