<?php $this->script("
    function resourceTabs() {
        $('.tabs').tabs();
    }
")?>
<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th width="180px"><?=__('User')?></th>
            <th><?=__('Roles')?></th>
            <th width="40px"></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $user): ?>
        <tr>
            <td>
                <a href="<?=$this->url('users', 'profile', ['id'=>$user->id])?>"><?=$user->login?></a>
            </td>
            <td><?=$user->rolesList?></td>
            <td>
                <a href="<?=$this->url('acl', 'edit-user', ['id' => $user->id]);?>" class="btn btn-primary btn-small dialog" data-ajax-method="get">
                    <i class="glyphicon glyphicon-pencil"></i>
                </a>
            </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>