<?php
/**
 * @var \Bluz\View\View $this
 * @var \Application\Users\Row $user
 */
?>
<form action="<?= $this->url('acl', 'user', ['id' => $user->id]) ?>" class="form-horizontal" data-ajax method="post"
      enctype="application/x-www-form-urlencoded">
  <div class="modal-header">
    <h4 class="modal-title"><?= __('Choose roles for %s', $user->login) ?></h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="<?=__('Close')?>">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div>
      <?php foreach ($roles as $i => $role): ?>
        <div class="form-group input-group">
            <span class="input-group-addon">
                <input id="i-<?= $i ?>" type="checkbox" name="roles[]" value="<?= $role->id ?>" <?= (!$user->hasRole(
                    $role->id
                ) ? '' : 'checked') ?>/>
            </span>
          <label for="i-<?= $i ?>" class="form-control"><?= $role->name ?></label>
        </div>
      <?php endforeach; ?>
    </div>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary"><?= __('Save changes') ?></button>
    <a href="#" class="btn btn-light" data-dismiss="modal"><?= __('Close') ?></a>
  </div>
</form>