<?php
/**
 * @var \Bluz\View\View $this
 * @var \Application\Users\Row $user
 */

?>
<form action="<?= $this->url('acl', 'user', ['id' => $user->id]) ?>" class="form-horizontal" method="post"
      data-ajax novalidate>
    <div class="modal-header">
        <h4 class="modal-title"><?= __('Choose roles for %s', $user->login) ?></h4>
        <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="modal"></button>
    </div>
    <div class="modal-body">
        <div>
            <?php
            foreach ($roles as $i => $role): ?>
                <div class="input-group mb-1">
            <span class="input-group-text">
              <input id="i-<?= $i ?>" type="checkbox" name="roles[]" value="<?= $role->id ?>" <?= (!$user->hasRole(
                  $role->id
              ) ? '' : 'checked') ?>/>
            </span>
                    <label for="i-<?= $i ?>" class="form-control"><?= $role->name ?></label>
                </div>
            <?php
            endforeach; ?>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary"><?= __('Save') ?></button>

        <button type="button" class="btn btn-light" data-bs-dismiss="modal"><?= __('Close') ?></button>
    </div>
</form>