<?php

/**
 * @var \Bluz\Grid\Grid $grid
 */
if (!$grid) {
    return;
}
?>
<?php
if ($grid->pages() > 1 && count($grid->getData()) < $grid->getLimit()) :
    $emptyRows = $grid->getLimit() - count($grid->getData()); ?>
    <table class="table">
        <?php
        for ($i = 0; $i < $emptyRows; $i++): ?>
            <tr>
                <td>&nbsp;</td>
            </tr>
        <?php
        endfor; ?>
    </table>
<?php
endif; ?>