<?php
/**
 * @var \Bluz\Grid\Grid $grid
 * @var array           $filters
 */
if (!$grid) {
    return;
}

$field = key($filters);
$value = ''; // filter value

$gridFilters = $grid->getFilters();

foreach ($filters as $filterName => $filterTitle) {
    if (isset($gridFilters[$filterName][$grid::FILTER_LIKE])) {
        $field = $filterName;
        $value = $gridFilters[$filterName][$grid::FILTER_LIKE];
        break;
    }
}
?>
<div class="input-group-btn grid-filter-search">
  <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <?= $filters[$field] ?>
  </button>
  <div class="dropdown-menu">
      <?php foreach ($filters as $fieldName => $fieldTitle) : ?>
          <a href="#" class="dropdown-item"
              data-filter="<?= $grid->getUid() . '-filter-' . $fieldName ?>"
              data-filter-type="<?= $grid::FILTER_LIKE ?>"
          >
              <?= $fieldTitle ?>
          </a>
      <?php endforeach; ?>
  </div>
</div><!-- /btn-group -->
<input name="<?= $grid->getUid() . '-filter-' . $field ?>" class="grid-filter-search-input"
       value="<?= $grid::FILTER_LIKE . '-' . esc($value) ?>" type="hidden"/>
<input name="search-like" type="search" class="form-control" value="<?= esc($value) ?>" required/>
