<?php

/**
 * @var \Bluz\Grid\Grid $grid
 */
if (!$grid) {
    return;
}
?>
<nav aria-label="<?= __('Total') ?>">
    <ul class="pagination float-start">
        <li class="page-item">
            <a href="<?= $grid->reset() ?>" class="page-link"><?= __('Total') ?>:
                <strong><?= $grid->total() ?></strong> <?= _n('record', 'records', $grid->total()) ?>
                <?= _n('on %s page', 'on %s pages', $grid->pages(), '<strong>' . $grid->pages() . '</strong>') ?></a>
        </li>
    </ul>
</nav>