<?php
/* @var \Application\Users\Row $user */

?>
<div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
            <?= $this->ahref(
                __('Profile'),
                ['users', 'profile'],
                ['class' => 'nav-link' . ($this->module('users') && $this->controller('profile') ? ' active' : '')]
            ) ?>
        </li>
        <?php
        if ($this->user() && $this->user()->getId() === $user->getId()) : // only for user
            ?>
            <?php
            if ($this->hasModule('profile')) : ?>
                <li class="nav-item">
                    <?= $this->ahref(
                        __('Change profile'),
                        ['users', 'change-profile'],
                        [
                            'class' => 'nav-link' . ($this->module('users') && $this->controller(
                                    'change-profile'
                                ) ? ' active' : '')
                        ]
                    ) ?>
                </li>
            <?php
            endif; ?>
            <li class="nav-item">
                <?= $this->ahref(
                    __('Change email'),
                    ['users', 'change-email'],
                    [
                        'class' => 'nav-link' . ($this->module('users') && $this->controller(
                                'change-email'
                            ) ? ' active' : '')
                    ]
                ) ?>
            </li>
            <li class="nav-item">
                <?= $this->ahref(
                    __('Change password'),
                    ['users', 'change-password'],
                    [
                        'class' => 'nav-link' . ($this->module('users') && $this->controller(
                                'change-password'
                            ) ? ' active' : '')
                    ]
                ) ?>
            </li>
        <?php
        endif; ?>
        <?php
        if ($this->hasModule('wallet') && $this->user()->getId() === $user->getId()) : ?>
            <li class="nav-item">
                <?= $this->ahref(
                    __('Wallet'),
                    ['wallet', 'index'],
                    ['class' => 'nav-link']
                ) ?>
            </li>
        <?php
        endif; ?>
    </ul>
</div>