<div class="well well-sm"> <?= esc($node['name']) ?>
    <div class="pull-right">
        <a href="<?= $this->url("categories", "crud", ["parentId" => $node['id']]) ?>"
           class="btn btn-xs btn-success dialog" data-ajax-method="get">
            <i class="fa fa-plus"></i>
        </a>
        <a href="<?= $this->url("categories", "crud", ["id" => $node['id']]) ?>"
           class="btn btn-primary btn-xs dialog" data-ajax-method="get" role="button">
            <i class="fa fa-pencil"></i>
        </a>
        <a href="<?= $this->url("categories", "crud", ["id" => $node['id']]) ?>"
           class="btn btn-xs btn-danger ajax confirm remove" data-ajax-method="delete" role="button">
            <i class="fa fa-trash-o"></i>
        </a>
    </div>
</div>