<?php
/** @var Application\Categories\Row $category */
$rootId = $category->rootId ?: $category->id;
?>
<div class="well well-sm"> <?= esc($category->name) ?>
    <div class="pull-right">
        <a href="<?= $this->url("categories", "crud", ["parentId" => $category->id, "rootId" => $rootId]) ?>"
           class="btn btn-xs btn-success dialog" data-ajax-method="get">
            <i class="fa fa-plus"></i>
        </a>
        <a href="<?= $this->url("categories", "crud", ["id" => $category->id, "rootId" => $rootId]) ?>"
           class="btn btn-primary btn-xs dialog" data-ajax-method="get" role="button">
            <i class="fa fa-pencil"></i>
        </a>
        <a href="<?= $this->url("categories", "crud", ["id" => $category->id]) ?>"
           class="btn btn-xs btn-danger ajax confirm remove" data-ajax-method="delete" role="button">
            <i class="fa fa-trash-o"></i>
        </a>
    </div>
</div>

<?php if ($children = $category->getChildren()) : ?>
    <ol class="tree">
        <?php foreach ($children as $child) : ?>
        <li>
            <?= $this->partial('partial/tree.phtml', ['category' => $child]) ?>
        </li>
        <?php endforeach;?>
    </ol>
<?php endif; ?>
