<?php $uid = uniqid('form_'); ?>
<form id="<?=$uid?>" action="<?=$this->url('options', 'crud')?>" class="form-horizontal ajax" method="<?=$method?>">
    <input type="hidden" name="id" value="<?=$row->id?>"/>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><?=__('Options')?></h4>
    </div>
    <div class="modal-body">
        <div class="form-group">
            <label class="control-label col-lg-2" for="name"><?=__('Namespace')?></label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="namespace" name="namespace" value="<?=esc($row->namespace)?:'default'?>" required />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="name"><?=__('Name')?></label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="name" name="name" value="<?=esc($row->name)?>" required />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="value"><?=__('Value')?></label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="value" name="value" value="<?=esc($row->value)?>" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label" for="value"><?=__('Description')?></label>
            <textarea class="form-control" id="description" name="description"><?=esc($row->description)?></textarea>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary"><?=__('Save')?></button>
        <a href="#" class="btn btn-default" data-dismiss="modal"><?=__('Close')?></a>
    </div>
</form>
<?php
// need for plain request
if (isset($errors)) :
    $data = json_encode(['errors'=>$errors]);
    $this->headScript('require(["bluz.form"], function(form) {
        form.notices($("#'.$uid.'"), '.$data.');
    });');
endif;
?>