<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
if (!$grid) return;
?>
<div class="clearfix" data-spy="grid" data-grid="<?=$grid->getUid()?>">
    <script>
        // use data-spy="grid" for use AJAX for reload grid
        require(['bluz.grid']);
    </script>

    <nav class="navbar navbar-default" role="navigation">
        <div class="col-lg-6">
            <a href="<?=$this->url('options', 'crud')?>" class="btn btn-primary navbar-btn dialog" data-ajax-method="get"><?=__('Create')?></a>
        </div>
        <div class="col-lg-6">

        </div>
    </nav>

    <?=$this->partial('grid/total.phtml', ['grid'=>$grid]) ?>
    <?=$this->partial('grid/limit.phtml', ['grid'=>$grid]) ?>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th width="80px"><a href="<?=$grid->order('namespace')?>"><?=__('Space')?></a></th>
                <th width="160px"><a href="<?=$grid->order('key')?>"><?=__('Key')?></a></th>
                <th><a href="<?=$grid->order('value')?>"><?=__('Value')?></a></th>
                <th width="160px"><a href="<?=$grid->order('created')?>"><?=__('Created')?></a></th>
                <th width="160px"><a href="<?=$grid->order('updated')?>"><?=__('Updated')?></a></th>
                <th width="72px"></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($grid->getData() as $row) : ?>
            <tr>
                <td><span class="label label-info"><?=$row['namespace']?></span></td>
                <td><a href="#" class="bluz-tooltip" data-toggle="tooltip" title="<?=esc($row['description'])?>"><?=esc($row['key'])?></a></td>
                <td>
                    <?php
                    $value = unserialize($row['value']);
                    if (is_array($value)) {
                        echo __('Array (length=%d)', sizeof($value));
                    } elseif (is_object($value)) {
                        echo __('Object of `%s` class', get_class($value));
                    } else {
                        echo esc($value);
                    }
                    ?>
                </td>
                <td><?=$row['created']?></td>
                <td><?=$row['updated']?></td>
                <td class="controls">
                    <a href="<?=$this->url('options', 'crud', ['key' => $row['key'], 'namespace' => $row['namespace']]);?>"
                       class="btn btn-xs btn-primary dialog" data-ajax-method="get">
                        <i class="fa fa-pencil"></i>
                    </a>
                    <a href="<?=$this->url('options', 'crud', ['key' => $row['key'], 'namespace' => $row['namespace']]);?>"
                       class="confirm btn btn-xs btn-danger ajax" data-ajax-method="delete">
                        <i class="fa fa-trash-o"></i>
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?=$this->partial('grid/empty-rows.phtml', ['grid'=>$grid]) ?>
    <?=$this->partial('grid/pagination.phtml', ['grid'=>$grid]) ?>
    <?=$this->partial('grid/total.phtml', ['grid'=>$grid]) ?>

</div>