<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
?>
<div class="clearfix" data-spy="grid" data-grid="<?=$grid->getUid()?>">
    <script>
        // use data-spy="grid" for use AJAX for reload grid
        require(['bluz.grid']);
    </script>

    <nav class="navbar navbar-default" role="navigation">
        <div class="col-lg-6">
            <a href="<?=$this->url('options', 'crud')?>" class="btn btn-primary navbar-btn dialog" data-ajax-method="get"><?=__('Create')?></a>
        </div>
        <div class="col-lg-6">

        </div>
    </nav>

    <?php $this->partial('grid/total.phtml', ['grid'=>$grid]) ?>
    <?php $this->partial('grid/limit.phtml', ['grid'=>$grid]) ?>

    <table class="table">
        <thead>
            <tr>
                <th width="40px"><?=__('Id')?></th>
                <th width="80px"><a href="<?=$grid->order('namespace')?>"><?=__('Space')?></a></th>
                <th width="160px"><a href="<?=$grid->order('name')?>"><?=__('Name')?></a></th>
                <th><a href="<?=$grid->order('value')?>"><?=__('Value')?></a></th>
                <th width="160px"><a href="<?=$grid->order('created')?>"><?=__('Created')?></a></th>
                <th width="160px"><a href="<?=$grid->order('updated')?>"><?=__('Updated')?></a></th>
                <th width="72px"></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($grid->getData() as $row) : ?>
            <tr>
                <td><?=$row['id']?></td>
                <td><span class="label"><?=$row['namespace']?></span></td>
                <td><a href="#" class="bluz-tooltip" data-toggle="tooltip" title="<?=esc($row['description'])?>"><?=esc($row['name'])?></a></td>
                <td><?=esc($row['value'])?></td>
                <td><?=$row['created']?></td>
                <td><?=$row['updated']?></td>
                <td class="controls">
                    <a href="<?=$this->url('options', 'crud', ['data' => ['id' => $row['id']]]);?>" class="btn btn-xs btn-primary dialog" data-ajax-method="get">
                        <i class="icon-pencil"></i>
                    </a>
                    <a href="<?=$this->url('options', 'crud', ['data' => ['id' => $row['id']]]);?>" class="confirm btn btn-xs btn-danger ajax" data-ajax-method="delete">
                        <i class="icon-trash"></i>
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php $this->partial('grid/empty-rows.phtml', ['grid'=>$grid]) ?>
    <?php $this->partial('grid/pagination.phtml', ['grid'=>$grid]) ?>
    <?php $this->partial('grid/total.phtml', ['grid'=>$grid]) ?>

</div>