<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
?>
<div data-spy="grid" data-grid="<?=$grid->getUid()?>">
    <script>
        // use data-spy="grid" for use AJAX for reload grid
        require(['bluz.grid']);
    </script>

    <div class="pagination pagination-right">
        <a href="<?=$this->url('options', 'crud')?>" class="btn btn-primary left dialog" data-ajax-method="get"><?=__('Create')?></a>
        <ul>
            <li><a href="#"><?=__('Limit')?></a></li>
            <li <?=(($grid->getLimit()==25)?'class="active"':'')?>><a href="<?=$grid->limit(25)?>">25</a></li>
            <li <?=(($grid->getLimit()==50)?'class="active"':'')?>><a href="<?=$grid->limit(50)?>">50</a></li>
            <li <?=(($grid->getLimit()==100)?'class="active"':'')?>><a href="<?=$grid->limit(100)?>">100</a></li>
        </ul>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th width="40px"><?=__('Id')?></th>
                <th width="80px"><a href="<?=$grid->order('namespace')?>"><?=__('Space')?></a></th>
                <th width="160px"><a href="<?=$grid->order('name')?>"><?=__('Name')?></a></th>
                <th><a href="<?=$grid->order('value')?>"><?=__('Value')?></a></th>
                <th width="160px"><a href="<?=$grid->order('created')?>"><?=__('Created')?></a></th>
                <th width="160px"><a href="<?=$grid->order('updated')?>"><?=__('Updated')?></a></th>
                <th width="100px"></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($grid->getData() as $row) : ?>
            <tr>
                <td><?=$row['id']?></td>
                <td><span class="label"><?=$row['namespace']?></span></td>
                <td><a href="#" class="bluz-tooltip" data-toggle="tooltip" title="<?=($row['description'])?>"><?=$row['name']?></a></td>
                <td><?=$row['value']?></td>
                <td><?=$row['created']?></td>
                <td><?=$row['updated']?></td>
                <td class="controls">
                    <a href="<?=$this->url('options', 'crud', ['data' => ['id' => $row['id']]]);?>" class="btn btn-small dialog" data-ajax-method="get">
                        <i class="icon-pencil"></i>
                    </a>
                    <a href="<?=$this->url('options', 'crud', ['data' => ['id' => $row['id']]]);?>" class="confirm btn btn-small btn-danger ajax" data-ajax-method="delete">
                        <i class="icon-white icon-trash"></i>
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
            <?php if (sizeof($grid->getData()) < $grid->getLimit()) :
                $emptyRows = $grid->getLimit() - sizeof($grid->getData()); ?>
                <?php for ($i = 0; $i < $emptyRows; $i++): ?>
                <tr>
                    <td colspan="7">&nbsp;</td>
                </tr>
                <?php endfor; ?>
            <?php endif; ?>
        </tbody>
    </table>
    <div class="pagination">
        <?php if ($grid->pages() > 1) : ?>
        <ul>
            <?php if ($prev = $grid->prev()) : ?><li><a href="<?=$prev?>">&laquo;</a></li>
            <?php else : ?> <li class="disabled"><a href="#" onclick="javascript: return false;">&laquo;</a></li>
            <?php endif; ?>


            <?php for ($page = 1; $page <= $grid->pages(); $page++) : ?>
            <li <?=($page==$grid->getPage()?'class="active"':'') ?>><a href="<?=$grid->page($page)?>"><?=$page?></a></li>
            <?php endfor; ?>

            <?php if ($next = $grid->next()) : ?><li><a href="<?=$next?>">&raquo;</a></li>
            <?php else : ?> <li class="disabled"><a href="#" onclick="javascript: return false;">&raquo;</a></li>
            <?php endif; ?>
        </ul>
        <?php endif; ?>

        <ul class="right">
            <li>
                <a href="<?=$grid->reset()?>"><?=__('Total')?>:
                    <strong><?=$grid->total()?></strong> <?=__('record','records', $grid->total())?> <?=__('on')?>
                    <strong><?=$grid->pages()?></strong> <?=__('page','pages', $grid->pages())?></a>
            </li>
        </ul>
    </div>

</div>