<?php $uid = uniqid('form_', false); ?>
<div class="card text-center">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
          <?= $this->ahref(__('Profile'), ['users', 'profile'], ['class' => 'nav-link']) ?>
      </li>
      <li class="nav-item">
          <?= $this->ahref(__('Change email'), ['users', 'change-email'], ['class' => 'nav-link']) ?>
      </li>
      <li class="nav-item">
          <?= $this->ahref(__('Change password'), ['users', 'change-password'], ['class' => 'nav-link active']) ?>
      </li>
    </ul>
  </div>
  <div class="card-body">
    <h4 class="card-title"><?= __('Change password') ?></h4>
    <div class="card w-50 center">
      <div class="card-body">
        <form id="<?= $uid ?>" action="<?= $this->url('users', 'change-password') ?>" class="ajax form-horizontal"
              method="POST">
          <input type="hidden" name="_method" value="PUT"/>
          <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-fw fa-lock"></i></span>
            <input type="password" class="form-control" name="password"
                   placeholder="<?= __('current password') ?>" required/>
          </div>
          <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-fw fa-lock"></i></span>
            <input type="password" class="form-control" name="new_password"
                   placeholder="<?= __('new password') ?>"/>
          </div>
          <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-fw fa-lock"></i></span>
            <input type="password" class="form-control" name="new_password2"
                   placeholder="<?= __('repeat password') ?>"/>
          </div>
          <button type="submit" class="btn btn-primary"><?= __('Save') ?></button>
        </form>
      </div>
    </div>
  </div>
</div>
