<?php $uid = uniqid('form_'); ?>
<h3 class="page-header"><?=__('Change email')?></h3>
<p><?=__('Email will be changed after confirmation')?></p>
<form id="<?=$uid?>" action="<?=$this->url('users', 'change-email')?>" class="ajax form-horizontal" method="POST">
    <div class="form-group input-group">
        <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
        <input type="email" class="form-control" name="email" value="<?=($email)?>" maxlength="255" required/>
    </div>
    <div class="form-group input-group">
        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
        <input type="password" class="form-control" name="password"
               placeholder="<?=__('current password')?>" required/>
    </div>
    <button type="submit" class="btn btn-primary"><?=__('Save')?></button>
</form>
