<?php $uid = uniqid('form_');?>
<h3 class="page-header"><?=__('Set your credentials')?></h3>
<form id="<?=$uid?>" action="<?=$this->url('users', 'change-credentials')?>" class="ajax form-horizontal" method="POST">
    <div class="form-group input-group">
        <span class="input-group-addon"><i class="fa fa-user"></i></span>
        <input type="text" class="form-control" name="login"
               placeholder="<?=__('login')?>" required/>
    </div>
    <div class="form-group input-group">
        <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
        <input type="text" class="form-control" name="email"
               placeholder="<?=__('email')?>" required/>
    </div>
    <div class="form-group input-group">
        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
        <input type="password" class="form-control" name="password"
               placeholder="<?=__('password')?>" required/>
    </div>
    <div class="form-group input-group">
        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
        <input type="password" class="form-control" name="password2"
               placeholder="<?=__('repeat your password')?>" required/>
    </div>
    <button type="submit" class="btn btn-primary"><?=__('Save')?></button>
</form>
