<?php $uid = uniqid('form_'); ?>
<h3 class="page-header"><?=__('Change password')?></h3>

<form id="<?=$uid?>" action="<?=$this->url('users', 'change-password')?>" class="ajax form-horizontal" method="POST">
    <input type="hidden" name="_method" value="PUT"/>
    <div class="form-group input-group">
        <span class="input-group-addon"><i class="fa fa-fw fa-lock"></i></span>
        <input type="password" class="form-control" name="password"
               placeholder="<?=__('current password')?>" required/>
    </div>
    <div class="form-group input-group">
        <span class="input-group-addon"><i class="fa fa-fw fa-lock"></i></span>
        <input type="password" class="form-control" name="new_password"
               placeholder="<?=__('new password')?>"/>
    </div>
    <div class="form-group input-group">
        <span class="input-group-addon"><i class="fa fa-fw fa-lock"></i></span>
        <input type="password" class="form-control" name="new_password2"
               placeholder="<?=__('repeat password')?>"/>
    </div>
    <button type="submit" class="btn btn-primary"><?=__('Save')?></button>
</form>
