<?php $uid = uniqid('form_'); ?>
<h3 class="page-header"><?=__('Change email')?></h3>
<p><?=__('Email will be changed after confirmation')?></p>
<form id="<?=$uid?>" action="<?=$this->url('users', 'change-email')?>" class="ajax form-horizontal" method="POST">
    <div class="form-group">
        <label class="sr-only" for="email"><?=__('Email')?></label>
        <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-fw fa-envelope" aria-hidden="true"></i></div>
            <input id="email" type="email" class="form-control" name="email" value="<?=($email)?>" maxlength="255" required/>
        </div>
    </div>
    <div class="form-group">
        <label class="sr-only" for="password"><?=__('Password')?></label>
        <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-fw fa-lock" aria-hidden="true"></i></div>
            <input id="password" type="password" class="form-control" name="password"
                   placeholder="<?=__('current password')?>" required/>
        </div>
    </div>
    <button type="submit" class="btn btn-primary"><?=__('Save')?></button>
</form>
