<?php /** @var \Bluz\View\View $this */ ?>
<?php $uid = uniqid('form_', false); ?>
<div class="card text-center">
  <?php require_once __DIR__ .'/partial/card-header.phtml' ?>
  <div class="card-body">
    <h4 class="card-title"><?= __('Change password') ?></h4>
    <div class="card w-50 center">
      <div class="card-body">
        <form id="<?= $uid ?>" action="<?= $this->url('users', 'change-password') ?>" class="form-horizontal" data-ajax
              method="POST">
          <input type="hidden" name="_method" value="PUT"/>
          <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-fw fa-lock"></i></span>
            <input type="password" class="form-control" name="password"
                   placeholder="<?= __('current password') ?>" required/>
          </div>
          <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-fw fa-lock"></i></span>
            <input type="password" class="form-control" name="new_password"
                   placeholder="<?= __('new password') ?>"/>
          </div>
          <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-fw fa-lock"></i></span>
            <input type="password" class="form-control" name="new_password2"
                   placeholder="<?= __('repeat password') ?>"/>
          </div>
          <button type="submit" class="btn btn-primary"><?= __('Save') ?></button>
        </form>
      </div>
    </div>
  </div>
</div>
