<?php
use Application\Users\Table;

$uid = uniqid('form_', false); ?>

<form id="<?= $uid ?>" action="<?= $this->url('users', 'crud') ?>" class="form-horizontal ajax" method="<?= $method ?>">
  <input type="hidden" name="id" value="<?= $row->id ?>"/>
  <div class="modal-header">
    <h4 class="modal-title"><?= __('Edit user') ?></h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="<?=__('Close')?>">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="form-group row">
      <label class="col-form-label col-lg-2" for="login"><?= __('Login') ?></label>
      <div class="col-lg-10">
        <input class="form-control" id="login" name="login" value="<?= ($row->login) ?>" maxlength="255" required/>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-form-label col-lg-2" for="email"><?= __('Email') ?></label>
      <div class="col-lg-10">
        <input type="email" class="form-control" id="email" name="email" value="<?= ($row->email) ?>" maxlength="255"
               required/>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-form-label col-lg-2" for="status"><?= __('Status') ?></label>
      <div class="col-lg-10">
        <select id="status" name="status" class="form-control">
          <option <?= $row->status === Table::STATUS_PENDING ? 'selected' : '' ?>>pending</option>
          <option <?= $row->status === Table::STATUS_ACTIVE ? 'selected' : '' ?>>active</option>
          <option <?= $row->status === Table::STATUS_DISABLED ? 'selected' : '' ?>>disabled</option>
          <option <?= $row->status === Table::STATUS_DELETED ? 'selected' : '' ?>>deleted</option>
        </select>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary"><?= __('Save') ?></button>
    <a href="#" class="btn btn-light" data-dismiss="modal"><?= __('Close') ?></a>
  </div>
</form>
<?php
// need for plain request
if (isset($errors)) :
    echo $this->partial('crud/errors.phtml', ['uid' => $uid, 'errors' => $errors]);
endif;
?>