<?php
use Application\Users\Table;

$uid = uniqid('form_'); ?>

<form id="<?=$uid?>" action="<?=$this->url('users', 'crud')?>" class="form-horizontal ajax" method="<?=$method?>">
    <input type="hidden" name="id" value="<?=$row->id?>"/>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><?=__('Edit user')?></h4>
    </div>
    <div class="modal-body">
        <div class="form-group">
            <label class="control-label col-lg-2" for="login"><?=__('Login')?></label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="login" name="login" value="<?=($row->login)?>" maxlength="255" required />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="email"><?=__('Email')?></label>
            <div class="col-lg-10">
                <input type="email" class="form-control" id="email" name="email" value="<?=($row->email)?>" maxlength="255" required />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="status"><?=__('Status')?></label>
            <div class="col-lg-10">
                <select id="status" name="status" class="form-control">
                    <option <?=$row->status == Table::STATUS_ACTIVE ?'selected':''?>>active</option>
                    <option <?=$row->status == Table::STATUS_DISABLED ?'selected':''?>>disabled</option>
                    <option <?=$row->status == Table::STATUS_PENDING ?'selected':''?>>pending</option>
                </select>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary"><?=__('Save')?></button>
        <a href="#" class="btn btn-default" data-dismiss="modal"><?=__('Close')?></a>
    </div>
</form>
<?php
// need for plain request
if (isset($errors)) :
    $data = json_encode(['errors'=>$errors]);
    $this->headScript('require(["bluz.form"], function(form) {
        form.notices($("#'.$uid.'"), '.$data.');
    });');
endif;
?>