<?
/**
 * @var \Application\Users\Row $user
 * @var \Bluz\View $this
 */
?>
<form action="<?= $this->url('users', 'login')?>" method="post" class="well">
    <label for="login">Login:</label>
    <input type="text" id="login" name="login" value="" />
    <label for="password">Password:</label>
    <input type="password" id="password" name="password" />
    <input type="submit" value="Login" class="btn btn-primary"/>
</form>