<?php
/**
 * @var \Application\Users\Row $user
 * @var \Bluz\View\View $this
 */
?>
<h3 class="page-header">
    <?=__('Profile')?>
    <?php if ($this->user()->id == $user->id) : ?>
        <?=$this->ahref(__('Edit profile'), ['users', 'edit'], ['class'=>'btn btn-mini btn-primary pull-right'])?>
    <?php endif; ?>
</h3>
<dl class="dl-horizontal">
    <dt><?=__('Name')?></dt>
    <dd><?=$user->login?></dd>
    <dt><?=__('Status')?></dt>
    <dd><?=$user->status?></dd>
</dl>

