<?php
/**
 * @var \Application\Users\Row $user
 * @var \Bluz\View\View        $this
 */
?>
<div class="card text-center">
  <?php require_once __DIR__ .'/partial/card-header.phtml' ?>
  <div class="card-body">
    <div class="card-group">
      <div class="card">
        <img class="card-img-top" id="avatar" src="<?= $this->gravatar($user->email, 360) ?>" alt="<?= $user->email ?>">
      </div>
      <div class="card">
          <?php if ($this->hasModule('profile')) : ?>
              <?= $this->dispatch('users', 'widgets/profile', ['id' => $user->id]) ?>
          <?php endif; ?>
        <ul class="list-group list-group-flush">
      </div>
      <div class="card">
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><h4 class="card-title"><?= $user->login ?></h4></li>
          <li class="list-group-item"><a href="mailto:<?= $user->email ?>"><?= $user->email ?></a></li>
          <li class="list-group-item"><?= __('Account status') ?>: <?= $user->status ?></li>
          <?php if ($this->user() && $this->user()->id === $user->id) : ?>
            <li class="list-group-item"><?= __('Linking to social networks') ?></li>
            <li class="list-group-item">
                <?php $this->hasModule('google') && $this->dispatch('google', 'widgets/auth'); ?>
                <?php $this->hasModule('facebook') && $this->dispatch('facebook', 'widgets/auth'); ?>
                <?php $this->hasModule('twitter') && $this->dispatch('twitter', 'widgets/auth'); ?>
            </li>
          <?php endif; ?>
        </ul>
      </div>
    </div>
  </div>
</div>
<?php if ($this->hasModule('media')) : ?>
<script>
  require(['jquery'], function($) {
    $('#avatar-button').on('push.bluz.data', function(event, data) {
      // send to server for update avatar
      // all information about image inside data
      $('#avatar').attr('src', data.thumb);
      // hide modal dialog
      $(this).data('modal').modal('hide');
    });
  });
</script>
<?php endif; ?>
