<?php
/**
 * @var \Application\Users\Row $user
 * @var \Bluz\View\View $this
 */
?>
<h3><?=__('Reset Password')?></h3>
<p><?=__('Hi %s, enter your new password', $user->login)?></p>
<form action="<?=$this->url('users', 'recovery-reset')?>" method="post" >
    <input type="hidden" name="code" value="<?=$code?>"/>
    <input type="hidden" name="id" value="<?=$user->id?>"/>
    <div class="control-group">
        <label class="input-prepend">
            <span class="add-on"><i class="icon-lock"></i></span>
            <input type="password" class="input-large" name="password" value="" placeholder="<?=__('new password')?>"/>
        </label>
    </div>
    <div class="control-group">
        <label class="input-prepend">
            <span class="add-on"><i class="icon-lock"></i></span>
            <input type="password" class="input-large" name="password2" value="" placeholder="<?=__('repeat password')?>"/>
        </label>
    </div>
    <input type="submit" value="<?=__('Change password')?>" class="btn btn-primary"/>
</form>