<?php
/**
 * @var \Application\Users\Row $user
 * @var \Bluz\View\View $this
 */
?>
<h3><?=__('Recovery Password')?></h3>
<form action="<?=$this->url('users', 'recovery')?>" method="post" >
    <div class="form-group">
        <label class="input-prepend">
            <span class="add-on"><i class="glyphicon glyphicon-envelope"></i></span><input type="text" id="email" name="email" class="input-large" value="<?=isset($email)?$email:''?>"  placeholder="<?=__('email')?>"/>
        </label>
    </div>
    <input type="submit" value="<?=__('Recovery')?>" class="btn btn-primary"/>
</form>