<?php
/**
 * @var \Application\Users\Row $user
 * @var \Bluz\View\View $this
 */
?>
<h3><?=__('Reset Password')?></h3>
<p><?=__('Hi %s, enter your new password', $user->login)?></p>
<form action="<?=$this->url('users', 'recovery-reset')?>" method="post" >
    <input type="hidden" name="code" value="<?=$code?>"/>
    <input type="hidden" name="id" value="<?=$user->id?>"/>
    <div class="form-group input-group">

        <span class="input-group-addon"><i class="fa fa-fw fa-lock"></i></span>
        <input type="password" class="form-control" name="password" value="" placeholder="<?=__('new password')?>"/>

    </div>
    <div class="form-group input-group">
        <span class="input-group-addon"><i class="fa fa-fw fa-lock"></i></span>
        <input type="password" class="form-control" name="password2" value="" placeholder="<?=__('repeat password')?>"/>
    </div>
    <input type="submit" value="<?=__('Change password')?>" class="btn btn-primary"/>
</form>