<?php
/**
 * @var \Application\Users\Row $user
 * @var \Bluz\View\View        $this
 */
?>
<div class="modal-header">
  <h3 class="modal-title"><?= __('Recovery Password') ?></h3>
</div>
<div class="modal-body">
  <form action="<?= $this->url('users', 'recovery') ?>" method="post" data-ajax>
    <div class="form-group input-group">
      <span class="input-group-addon"><i class="fa fa-fw fa-envelope"></i></span>
      <input type="email" id="email" name="email" class="form-control" value="<?= isset($email) ? $email : '' ?>"
             placeholder="<?= __('email') ?>" maxlength="255" required/>
    </div>
    <input type="submit" value="<?= __('Recovery') ?>" class="btn btn-primary"/>
  </form>
</div>
<div class="modal-footer clearfix"></div>
