<?php $uid = uniqid('form_'); ?>

<script>
    function validateForm (data) {
        $('#<?=$uid?>').find('.control-group').removeClass('error');
        $('#<?=$uid?>').find('.help-inline.error').remove();
        if (data.errors) {
            $.each(data.errors, function(field, messages) {
                $('#<?=$uid?>').find('.control-group:has(#'+field+')').addClass('error');
                $.each(messages, function(i, msg){
                    $('#'+field).parent('.controls') // <div class="controls">..</div>
                        .append('<span class="help-inline error">'+msg+'</span>');
                });
            });
        }
    }
</script>
<div class="row-fluid">
<form id="<?=$uid?>" action="<?=$this->url('users', 'registration')?>" class="form-horizontal ajax" method="post">
    <input type="hidden" name="data[id]" value="<?=$row->id?>"/>
    <div class="span6">
        <div class="modal-header">
            <h3>Registration</h3>
        </div>
        <div class="modal-body">
            <div class="control-group">
                <label class="control-label" for="login"><?=$this->__('Login')?></label>
                <div class="controls">
                    <input type="text" class="input-xlarge" id="login" name="data[login]" value="<?=($row->login)?>" />
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="email"><?=$this->__('Email')?></label>
                <div class="controls">
                    <input type="text" class="input-xlarge" id="email" name="data[email]" value="<?=($row->email)?>" />
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary"><?=$this->__('Registration')?></button>
        </div>
    </div>
</form>
</div>
