<?php $uid = uniqid('form_'); ?>

<form id="<?=$uid?>" action="<?=$this->url('users', 'signup')?>" class="ajax" method="post">
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?=__('Registration')?></h3>
    </div>
    <div class="panel-body">
        <input type="hidden" name="id" value="<?=$row->id?>"/>
        <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
            <input type="text" class="form-control" name="login" value="<?=($row->login)?>" placeholder="<?=__('login')?>" maxlength="255" required />
        </div>
        <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-envelope fa-fw"></i></span>
            <input type="email" class="form-control" name="email" value="<?=($row->email)?>" placeholder="<?=__('email')?>" maxlength="255" required />
        </div>
        <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-lock fa-fw"></i></span>
            <input type="password" class="form-control" name="password" value="<?=($row->password)?>" placeholder="<?=__('password')?>" required />
        </div>
        <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-lock fa-fw"></i></span>
            <input type="password" class="form-control" name="password2" value="<?=($row->password2)?>" placeholder="<?=__('repeat password')?>" required />
        </div>
    </div>
    <div class="panel-footer">
        <button type="submit" class="btn btn-primary"><?=__('Registration')?></button>
    </div>
</div>

</form>