<?php
/**
 * @var \Application\Users\Row $user
 * @var \Bluz\View\View $this
 */
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?=__('Please sign in')?></h3>
    </div>
    <div class="panel-body">
        <form action="<?=$this->url('users', 'signin')?>" method="post">
            <div class="form-group input-group">
                <span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
                <input type="text" name="login" class="form-control" value="<?=isset($login)?$login:''?>" placeholder="<?=__('login')?>" maxlength="255" required />
            </div>

            <div class="form-group input-group">
                <span class="input-group-addon"><i class="fa fa-lock fa-fw"></i></span>
                <input type="password" name="password" class="form-control" placeholder="<?=__('password')?>" required />
            </div>

            <div class="checkbox">
                <label>
                    <input type="checkbox" name="rememberMe" value="1" checked /> <?=__('Remember me')?>
                </label>
            </div>

            <input type="submit" value="<?=__('Sign In')?>" class="btn btn-primary"/>

            <a href="<?=$this->url('users', 'signup')?>" title="Sign Up" class="btn btn-default pull-right"><?=__('Sign Up')?></a>

        </form>
    </div>
    <div class="panel-footer clearfix">
        <div class="pull-left">
            <a href="<?=\Bluz\Proxy\Router::getUrl('auth', 'auth')?>" data-provider="google" class="provider btn fa fa-google-plus-square fa-2x"></a>
        </div>
        <div class="pull-left">
            <a href="<?=\Bluz\Proxy\Router::getUrl('auth', 'auth')?>" data-provider="facebook" class="provider btn fa fa-facebook-square fa-2x"></a>
        </div>
        <div class="pull-left">
            <a href="<?=\Bluz\Proxy\Router::getUrl('auth', 'auth')?>" data-provider="twitter" class="provider btn fa fa-twitter-square fa-2x"></a>
        </div>
        <a href="<?=$this->url('users', 'recovery')?>" class="pull-right"><?=__('Forgot your password?')?></a>
    </div>

</div>
