<?php
/**
 * @var \Application\Users\Row $user
 * @var \Bluz\View\View $this
 */
?>
<?= $this->headStyle('/css/font-awesome.min.css') ?>
<h3><?=__('Please sign in')?></h3>
<form action="<?=$this->url('users', 'signin')?>" method="post" >
    <div class="control-group">
        <label class="input-prepend">
            <span class="add-on"><i class="icon-user"></i></span><input type="text" id="login" name="login" class="input-large" value="<?=isset($login)?$login:''?>" placeholder="<?=__('login')?>" />
        </label>
    </div>
    <div class="control-group">
        <label class="input-prepend">
            <span class="add-on"><i class="icon-lock"></i></span><input type="password" id="password" name="password" class="input-large" placeholder="<?=__('password')?>" />
        </label>
    </div>
    <input type="submit" value="<?=__('Sign In')?>" class="btn btn-primary"/>
    <span class="social-auth">
        <?=$this->widget('twitter', 'auth')?>
        <?=$this->widget('facebook', 'auth')?>
    </span>
    <a href="<?=$this->url('users', 'signup')?>" title="Sign Up" class="btn right"><?=__('Sign Up')?></a>
</form>
<a href="<?=$this->url('users', 'recovery')?>"><?=__('Forgot your password?')?></a>