<?php $uid = uniqid('form_'); ?>
<h3><?=__('Registration')?></h3>
<form id="<?=$uid?>" action="<?=$this->url('users', 'signup')?>" class="ajax" method="post">
    <input type="hidden" name="data[id]" value="<?=$row->id?>"/>

    <div class="form-group">
        <label class="input-prepend">
            <span class="add-on"><i class="glyphicon glyphicon-user"></i></span>
            <input type="text" class="input-large" name="data[login]" value="<?=($row->login)?>" placeholder="<?=__('login')?>" required />
        </label>
    </div>
    <div class="form-group">
        <label class="input-prepend">
            <span class="add-on"><i class="glyphicon glyphicon-envelope"></i></span>
            <input type="text" class="input-large" name="data[email]" value="<?=($row->email)?>" placeholder="<?=__('email')?>" required />
        </label>
    </div>
    <div class="form-group">
        <label class="input-prepend">
            <span class="add-on"><i class="glyphicon glyphicon-lock"></i></span>
            <input type="password" class="input-large" name="data[password]" value="<?=($row->password)?>" placeholder="<?=__('password')?>" required />
        </label>
    </div>
    <div class="form-group">
        <label class="input-prepend">
            <span class="add-on"><i class="glyphicon glyphicon-lock"></i></span>
            <input type="password" class="input-large" name="data[password2]" value="<?=($row->password2)?>" placeholder="<?=__('repeat password')?>" required />
        </label>
    </div>
    <button type="submit" class="btn btn-primary"><?=__('Registration')?></button>
</form>
