<div class="modal-content">
    <div class="modal-header">
        <h4 class="modal-title"><?= __('Log file') ?></h4>
        <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="modal"></button>
    </div>
    <div class="modal-body">
        <p><?= $file ?></p>
        <pre style="max-height:60vh"><?php
            $handle = @fopen($file, 'rb');
            if ($handle) {
                while (($buffer = fgets($handle, 4096)) !== false) {
                    echo $buffer;
                }
                if (!feof($handle)) {
                    echo "Error: unexpected fgets() fail\n";
                }
                fclose($handle);
            }
            ?></pre>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-bs-dismiss="modal"><?= __('Close') ?></button>
    </div>
</div>
