<div class="jumbotron">
    <div class="container">
        <h1>Congratulations!</h1>
        <p>You have successfully installed the Skeleton application for <a href="https://github.com/bluzphp">Bluz Framework</a></p>
    </div>
</div>

<h2>What next?</h2>

<div class="panel-group" id="accordion">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">
                    Database setup &rarr;
                </a>
            </div>
        </div>
        <div id="collapseFour" class="panel-collapse collapse">
            <div class="panel-body">
                <p>Just two step for setup database</p>
                <ol>
                    <li>
                        Setup DB configuration in <code>./application/configs/production/db.php</code> file
                    </li>
                    <li>
                        Run phinx migration <code>./vendor/bin/phinx migrate</code>
                    </li>
                </ol>
                <div class="text-muted">
                    <p>Also you can setup configuration for development environment</p>
                    <ol>
                        <li>
                            setup environment <code>export BLUZ_ENV=<strong>dev</strong></code>
                        </li>
                        <li>
                            setup configuration in <code>application/configs/<strong>dev</strong>/db.php</code> file
                        </li>
                        <li>
                            run phinx migration <code>/path/to/vendor/bin/phinx migrate</code>
                        </li>
                    </ol>
                </div>
                <p>
                    Than you can run phinx seeds <code>/path/to/vendor/bin/phinx seed:run</code> for create
                    default example of pages and other stuff
                </p>
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFive">
                    Login as administrator &rarr;
                </a>
            </div>
        </div>
        <div id="collapseFive" class="panel-collapse collapse">
            <div class="panel-body">
                <p>
                    Try to login with login <code>admin</code> and password <code>admin</code>
                </p>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                    Create your first controller &rarr;
                </a>
            </div>
        </div>
        <div id="collapseOne" class="panel-collapse collapse">
            <div class="panel-body">
                <ol>
                    <li>create new folder <code>./application/modules/my</code>, where <code>my</code> it's module name </li>
                    <li>create new subfolder <code>./application/modules/my/controllers</code></li>
                    <li>create file <code>./application/modules/my/controllers/index.php</code></li>
                </ol>
<pre><code><strong>&lt;?php</strong>
return
    <em>/**
    * @param string $question
    * @return \closure
    */</em>
    function(<var>$question</var> = null) {
        <em>/**
        * @var Controller $this
        */</em>
        switch ($question) {
            case <span>'2+2'</span>:
            case <span>'2x2'</span>:
                <var>$answer</var> = 4;
                break;
            case <span>'6x8'</span>:
                <var>$answer</var> = 48;
                break;
            default:
                <var>$answer</var> = 42;
        }
        return [
            <span>"question"</span> => <var>$question</var>,
            <span>"answer"</span> = <var>$answer</var>
        ];
    };</code></pre>

            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                    Create view &rarr;
                </a>
            </div>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse">
            <div class="panel-body">
                <ol>
                    <li>create new subfolder <code>./application/modules/my/views</code></li>
                    <li>create file <code>./application/modules/my/views/index.phtml</code></li>
                </ol>
<pre><code>&lt;p&gt;
<strong>&lt;?php</strong> if (<var>$question</var>) : <strong>?&gt;</strong>
Q: <strong>&lt;?=</strong>esc(<var>$question</var>)<strong>?&gt;</strong>
<strong>&lt;php?</strong> endif; <strong>?&gt;</strong>
A: <strong>&lt;?=</strong>esc(<var>$answer</var>)<strong>?&gt;</strong>
&lt;/p&gt;
</code></pre>
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
                    Run &rarr;
                </a>
            </div>
        </div>
        <div id="collapseThree" class="panel-collapse collapse">
            <div class="panel-body">
                Try to run:
                <ul>
                    <li><a href="<?=$this->baseUrl('/my/');?>"><?=$this->baseUrl('/my/');?></a></li>
                    <li><a href="<?=$this->baseUrl('/my/index/question/2+2');?>"><?=$this->baseUrl('/my/index/question/2+2');?></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
