<?php
/** @var \Bluz\View\View $this */ ?>
<h2>What next?</h2>
<hr/>

<div class="accordion" id="setup">
    <div class="accordion-item">
        <h2 class="accordion-header" id="setupHeadingOne">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#setupCollapseOne"
                    aria-expanded="true" aria-controls="collapseOne">
                Database setup &rarr;
            </button>
        </h2>
        <div id="setupCollapseOne" class="accordion-collapse collapse" aria-labelledby="setupHeadingOne"
             data-bs-parent="#setup">
            <div class="accordion-body">
                <p>Just two step for setup database</p>
                <ol>
                    <li>
                        Setup DB configuration in <code>./application/configs/production/db.php</code> file
                    </li>
                    <li>
                        Run phinx migration <code>./vendor/bin/bluzman db:migrate</code>
                    </li>
                </ol>
                <div class="text-muted">
                    <p>Also you can setup configuration for development environment</p>
                    <ol>
                        <li>
                            setup environment <code>export BLUZ_ENV=<strong>dev</strong></code>
                        </li>
                        <li>
                            setup configuration in <code>application/configs/<strong>dev</strong>/db.php</code> file
                        </li>
                        <li>
                            run phinx migration <code>./vendor/bin/bluzman db:migrate --env <strong>dev</strong></code>
                        </li>
                        <li>
                            copy <code>./public/.htaccess.dev.sample</code> to <code>./public/.htaccess</code>
                        </li>
                    </ol>
                </div>
                <p>
                    Than you can run phinx seeds <code>./vendor/bin/bluzman db:seed:run</code> for create
                    default example of pages and other stuff
                </p>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="setupHeadingTwo">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#setupCollapseTwo" aria-expanded="false" aria-controls="setupCollapseTwo">
                Login as administrator &rarr;
            </button>
        </h2>
        <div id="setupCollapseTwo" class="accordion-collapse collapse" aria-labelledby="setupHeadingTwo"
             data-bs-parent="#setup">
            <div class="accordion-body">
                <p>
                    Now you can
                    <?= $this->ahref(
                        __('sign in'),
                        ['users', 'signin'],
                        ['data-ajax-dialog', 'data-ajax-method' => 'get']
                    ) ?>
                    to system with login <code>admin</code> and password <code>admin</code>
                </p>
                <p>
                    Don't forget to change your password at profile page <?= $this->ahref(
                        'Profile page',
                        ['users', 'change-password']
                    ) ?>
                </p>
            </div>
        </div>
    </div>
</div>

<br/>

<h2>Are you developer?</h2>
<hr/>



<div class="accordion" id="develop">
    <div class="accordion-item">
        <h2 class="accordion-header" id="developHeadingOne">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#developCollapseOne" aria-expanded="true" aria-controls="developCollapseOne">
                Create your first controller &rarr;
            </button>
        </h2>
        <div id="developCollapseOne" class="accordion-collapse collapse" aria-labelledby="developHeadingOne" data-bs-parent="#develop">
            <div class="accordion-body">
                <ol>
                    <li>create new folder <code>./application/modules/my</code>, where <code>my</code> it's module name
                    </li>
                    <li>create new subfolder <code>./application/modules/my/controllers</code></li>
                    <li>create file <code>./application/modules/my/controllers/index.php</code></li>
                </ol>
                <pre><code><strong>&lt;?php</strong>
<em>/**
 * @param string $question
 * @return array
 */</em>
return function(<var>$question</var> = null) {
        <em>/**
        * @var Controller $this
        */</em>
        switch ($question) {
            case <span>'2+2'</span>:
            case <span>'2x2'</span>:
                <var>$answer</var> = 4;
                break;
            case <span>'6x8'</span>:
                <var>$answer</var> = 48;
                break;
            default:
                <var>$answer</var> = 42;
        }
        return [
            <span>"question"</span> => <var>$question</var>,
            <span>"answer"</span> = <var>$answer</var>
        ];
    };</code></pre>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="developHeadingTwo">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#developCollapseTwo" aria-expanded="false" aria-controls="developCollapseTwo">
                Create view &rarr;
            </button>
        </h2>
        <div id="developCollapseTwo" class="accordion-collapse collapse" aria-labelledby="developHeadingTwo" data-bs-parent="#develop">
            <div class="accordion-body">
                <ol>
                    <li>create new subfolder <code>./application/modules/my/views</code></li>
                    <li>create file <code>./application/modules/my/views/index.phtml</code></li>
                </ol>
                <pre><code>&lt;p&gt;
<strong>&lt;?php</strong> if (<var>$question</var>) : <strong>?&gt;</strong>
Q: <strong>&lt;?=</strong>esc(<var>$question</var>)<strong>?&gt;</strong>
<strong>&lt;php?</strong> endif; <strong>?&gt;</strong>
A: <strong>&lt;?=</strong>esc(<var>$answer</var>)<strong>?&gt;</strong>
&lt;/p&gt;
</code></pre>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="developHeadingThree">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#developCollapseThree" aria-expanded="false" aria-controls="developCollapseThree">
                Run &rarr;
            </button>
        </h2>
        <div id="developCollapseThree" class="accordion-collapse collapse" aria-labelledby="developHeadingThree" data-bs-parent="#develop">
            <div class="accordion-body">
                Check the result:
                <ul>
                    <li><a href="<?= $this->baseUrl('/my/'); ?>"><?= $this->baseUrl('/my/'); ?></a></li>
                    <li><a href="<?= $this->baseUrl('/my/index/question/2+2'); ?>"><?= $this->baseUrl(
                                '/my/index/question/2+2'
                            ); ?></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
