<div class="card">
    <div class="card-header"><?= __('User profile') ?></div>
    <img class="card-img-top" src="<?= $this->gravatar($user->email, 320) ?>" alt="Card image cap">
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <?= $user->login ?>
        </li>
        <li class="list-group-item">
            <a href="mailto:<?= $user->email ?>"><?= $user->email ?></a>
        </li>
        <li class="list-group-item">
            <?= $user->created ?>
        </li>
    </ul>
    <div class="card-body d-flex justify-content-around">
        <a href="<?= $this->url('users', 'profile', ['id' => $user->id]); ?>" class="btn btn-info"
           data-ajax-dialog data-ajax-method="get" data-modal-style="modal-lg">
            <i class="bi bi-person"></i> <?= __('Profile') ?>
        </a>
        <a href="<?= $this->url('users', 'crud', ['id' => $user->id]) ?>" class="btn btn-primary"
           data-ajax-dialog data-ajax-method="get">
            <i class="bi bi-pencil"></i> <?= __('Edit') ?>
        </a>
        <a href="<?= $this->url('acl', 'user', ['id' => $user->id]); ?>" class="btn btn-secondary"
           data-ajax-dialog data-ajax-method="get">
            <i class="bi bi-key"></i> <?= __('Roles') ?>
        </a>
    </div>
</div>
