<?php
/**
 * @var \Bluz\View\View $this
 */
?>
<?php $uid = uniqid('form_'); ?>
<form id="<?=$uid?>" action="<?=$this->url('media', 'crud')?>" class="form-horizontal" method="POST" enctype="multipart/form-data">
    <input type="hidden" name="_method" value="<?=$method?>"/>
    <input type="hidden" name="id" value="<?=$row->id?>"/>
    <div>
        <h3><?=__('Media')?></h3>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <div class="form-group">
                <label class="control-label col-lg-2" for="name"><?=__('Title')?></label>
                <div class="col-lg-10">
                    <input type="text" class="form-control" id="name" name="title" value="<?=($row->title)?>" required />
                </div>
            </div>
        <?php if ($method == 'POST') : ?>
            <div class="form-group">
                <label class="control-label col-lg-2"><?=__('File')?></label>
                <div class="col-lg-10">
                    <input type="file" name="file" accept="image/*" required />
                </div>
            </div>
        <?php else: ?>
            <div class="form-group">
                <label class="control-label col-lg-2"><?=__('File')?></label>
                <div class="col-lg-10">
                    <input type="text" class="form-control" readonly name="file" value="<?=($row->file)?>" />
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-lg-2"><?=__('Type')?></label>
                <div class="col-lg-10">
                    <input type="text" class="form-control" readonly name="type" value="<?=($row->type)?>" />
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-lg-2"><?=__('Link')?></label>
                <div class="col-lg-10">
                    <p class="form-control-static">
                        <a href="<?=$this->baseUrl($row->file)?>">
                            <?=\Bluz\Proxy\Router::getFullUrl().($row->file)?>
                        </a>
                    </p>
                </div>
            </div>
        <?php
            if (substr($row->type, 0, 5) == 'image') :
        ?>
        </div>
        <div class="form-group col-lg-2">
            <a href="<?=$this->baseUrl($row->file)?>" class="thumbnail bluz-preview">
                <img src="<?=$this->baseUrl($row->thumb?:$row->file)?>" class="img-polaroid" alt="<?=$row->title?>" />
            </a>
        <?php
            endif;
        ?>
        <?php endif; ?>
        </div>
    </div>
    <div>
        <button type="submit" class="btn btn-primary"><?=__('Save')?></button>
    </div>
</form>
<?php
// need for plain request
if (isset($errors)) :
    $data = json_encode(['errors'=>$errors]);
    $this->headScript('require(["bluz.form"], function(form) {
        form.notices($("#'.$uid.'"), '.$data.');
    });');
endif;
?>