<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
if (!$grid) return;
?>
<script>
    // use data-spy="grid" for use AJAX for reload grid
    require(['bluz.grid']);
</script>
<div class="clearfix" data-spy="grid" data-grid="<?=$grid->getUid()?>">

    <nav class="navbar navbar-default" role="navigation">
        <div class="col-lg-6">
            <a href="<?=$this->url('media', 'crud')?>" class="btn btn-primary navbar-btn"><?=__('Create')?></a>
        </div>
        <div class="col-lg-6">
            <form action="<?=$this->url('media', 'grid')?>" class="navbar-form filter-form pull-right">
                <div class="input-group">
                    <?php echo
                    $this->partial(
                        'grid/filter-search.phtml',
                        [
                            'grid' => $grid,
                            'filters' => [
                                'title' => __('Title'),
                                'file' => __('File'),
                            ]
                        ]
                    )
                    ?>
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><?=__("Search")?></button>
                    </span>
                </div>
            </form>
        </div>
    </nav>

    <?=$this->partial('grid/total.phtml', ['grid'=>$grid]) ?>
    <?=$this->partial('grid/limit.phtml', ['grid'=>$grid]) ?>
    <?php if ($grid->total()) : ?>
    <div class="pull-right">&nbsp;</div>
    <ul class="pagination pagination-small pull-right">
        <li class="disabled"><a href="#"><?=__('Image quantity')?></a></li>
        <li <?=(($countCol==2)?'class="active"':'')?>><a href="<?=$this->url('media', 'grid', ['countCol' => 2]);?>">2</a></li>
        <li <?=(($countCol==4)?'class="active"':'')?>><a href="<?=$this->url('media', 'grid', ['countCol' => 4]);?>">4</a></li>
    </ul>
    <?php endif; ?>

    <div class="row clearfix">
        <div class="col-lg-12">
            <?php
            $count = 0;
            foreach ($grid->getData() as $row) {
                if ($count == 0) {
                    echo '<div class="row">';
                }
            ?>
                <div class="col-lg-<?=$col?>">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="row">
                            <div class="col-lg-7 text-overflow">
                                <?=$row['title']?>
                            </div>
                            <div class="col-lg-5 text-right">
                                <a href="<?=$this->url('media', 'crud', ['id' => $row['id']])?>" class="btn btn-xs btn-primary ">
                                    <i class="fa fa-pencil"></i>
                                </a>
                                <a href="<?=$this->url('media', 'crud', ['id' => $row['id']])?>" class="confirm btn btn-xs btn-danger ajax" data-ajax-method="delete">
                                    <i class="fa fa-trash-o"></i>
                                </a>
                            </div>
                            </div>
                        </div>
                        <div class="panel-body" style="padding: 0">
                            <!-- use image as background -->
                            <a href="<?=$this->baseUrl($row['file'])?>"
                               style="display:block; overflow: hidden; height:<?=$col*50?>px; background: url(<?=$this->baseUrl($row['thumb'])?>) 50% 50% no-repeat; background-size: contain;"
                               class="bluz-preview"></a>
                        </div>
                        <div class="panel-footer">
                            <a href="<?=$this->url('users', 'profile', ['id'=>$row['userId']])?>">
                                <?=$row['login']?>
                            </a>
                            <div class="pull-right"><?=substr($row['created'], 0, -9)?></div>
                        </div>
                    </div>
                </div>

            <?php
                $count++;
                if ($count == $countCol) {
                    echo '</div>';
                    $count = 0;
                }
            };
            ?>
        </div>
    </div>

    <?=$this->partial('grid/empty-rows.phtml', ['grid'=>$grid]) ?>
    <?=$this->partial('grid/pagination.phtml', ['grid'=>$grid]) ?>
    <?=$this->partial('grid/total.phtml', ['grid'=>$grid]) ?>

</div>