<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
?>
<script xmlns="http://www.w3.org/1999/html">
    // use data-spy="grid" for use AJAX for reload grid
    require(['bluz.grid']);
</script>
<div class="clearfix" data-spy="grid" data-grid="<?=$grid->getUid()?>">

    <div class="navbar">
        <div class="row">
            <div class="col-lg-6">
                <a href="<?=$this->url('media', 'crud')?>" class="btn btn-primary navbar-btn"><?=__('Create')?></a>
            </div>
            <div class="col-lg-6">
                <form action="<?=$this->url('media', 'grid')?>" class="navbar-form filter-form pull-right">
                    <div class="input-group">
                        <?php
                        $this->partial(
                            'grid/filter-search.phtml',
                            [
                                'grid' => $grid,
                                'filters' => [
                                    'title' => __('Title'),
                                    'file' => __('File'),
                                ]
                            ]
                        )
                        ?>
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><?=__("Search")?></button>
                    </span>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <?php $this->partial('grid/total.phtml', ['grid'=>$grid]) ?>
    <?php $this->partial('grid/limit.phtml', ['grid'=>$grid]) ?>

    <ul class="pagination pagination-small pull-right">
        <li class="disabled"><a href="#"><?=__('Quantity image')?></a></li>
        <li <?=(($countCol==1)?'class="active"':'')?>><a href="<?=$this->url('media', 'grid', ['countCol' => 1]);?>">1</a></li>
        <li <?=(($countCol==2)?'class="active"':'')?>><a href="<?=$this->url('media', 'grid', ['countCol' => 2]);?>">2</a></li>
        <li <?=(($countCol==3)?'class="active"':'')?>><a href="<?=$this->url('media', 'grid', ['countCol' => 3]);?>">3</a></li>
        <li <?=(($countCol==4)?'class="active"':'')?>><a href="<?=$this->url('media', 'grid', ['countCol' => 4]);?>">4</a></li>
        <li <?=(($countCol==5)?'class="active"':'')?>><a href="<?=$this->url('media', 'grid', ['countCol' => 5]);?>">5</a></li>
        <li <?=(($countCol==6)?'class="active"':'')?>><a href="<?=$this->url('media', 'grid', ['countCol' => 6]);?>">6</a></li>
    </ul>


    <div class="row">
        <div class="col-lg-12">
            <?php
            $count = 0;
            foreach ($grid->getData() as $row) {
                if ($count == 0) {
                    echo '<div class="row">';
                }
                ?>

                <div class="col-lg-<?=$col?>">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <P>
                                <span ><?=$row['title']?></span>
                                <span class="pull-right" ><?=substr($row['created'], 0, -9)?>
                            </p>
                        </div>
                        <img style="height:<?=$col*50?>px" class="img-thumbnail"src="<?=$row['preview']?>">

                        <div class="panel-footer">
                            <P align="right">
                                <a class="pull-left" href="<?=$this->url('users', 'profile', ['id'=>$row['userId']]);?>" >
                                    <?=$row['login']?>
                                </a>
                                <a href="<?=$this->url('media', 'crud', ['data' => ['id' => $row['id']]]);?>" class="btn btn-small btn-primary">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                </a>
                                <a href="<?=$this->url('media', 'crud', ['data' => ['id' => $row['id']]]);?>" class="confirm btn btn-small btn-danger ajax" data-ajax-method="delete">
                                    <i class="glyphicon glyphicon-trash"></i>
                                </a>
                            </P>
                        </div>
                    </div>
                </div>

                <?php
                $count++;
                if ($count == $countCol) {
                    echo '</div>';
                    $count = 0;
                }
            };
            ?>
        </div>
    </div>

    <?php $this->partial('grid/empty-rows.phtml', ['grid'=>$grid]) ?>
    <?php $this->partial('grid/pagination.phtml', ['grid'=>$grid]) ?>
    <?php $this->partial('grid/total.phtml', ['grid'=>$grid]) ?>

</div>