<script>
    require(['bluz.media']);
</script>

<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><?=__('Images')?></h4>
    </div>

    <div class="modal-body">

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active">
                <a href="#upload" aria-controls="upload" role="tab" data-toggle="tab"><?=__('Upload')?></a>
            </li>
            <li role="presentation">
                <a href="#grid" aria-controls="grid" role="tab" data-toggle="tab"><?=__('List')?></a>
            </li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="upload">
                <div id="media-droparea"><div id="media-droparea-placeholder"><?=__('Drop file here or ')?><input type="file" name="file"></div></div>
            </div>
            <div role="tabpanel" class="tab-pane row" id="grid">
                <?php foreach ($images as $image) : ?>
                    <div class="col-xs-4 col-md-2">
                        <div class="thumbnail" data-id="<?=$image->id?>" data-preview="<?=$image->preview?>" data-preview="<?=$image->preview?>" >
                            <div style="background-image: url(<?=$this->baseUrl($image->preview)?>);"><!-- thumbnail --></div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>

    </div>
</div>

<!-- Styles -->
<style>
    #upload, #grid {
        padding: 8px;
        height: 360px;
        overflow: auto;
    }
    #grid .thumbnail > div {
        height: 128px;
        overflow: hidden;
        cursor: pointer;
        background-position: 50% 50%;
        background-repeat: no-repeat;
    }
    #media-droparea {
        position: relative;
        overflow: hidden;
        padding: 148px 24px;
        border: 3px dashed rgba(0, 0, 0, 0.1);
    }
    #media-droparea-placeholder {
        text-align: center;
        font-size: 12px;
        margin: auto;
        color: rgba(0, 0, 0, 0.7);
    }
    #media-droparea-placeholder input {
        display: inline-block;
    }
</style>
