<?php
use Bluz\Application\Application;
// for IDE syntax highlighter
/** @var $key */
$on = "javascript:(function(){document.cookie='BLUZ_DEBUG=1;path=/;';window.location.reload();})()";
$off = "javascript:(function(){document.cookie='BLUZ_DEBUG=;expires=Mon,%2005%20Jul%202000%2000:00:00%20GMT;path=/;';window.location.reload();})()";

$profilerOn = "javascript:(function(){document.cookie='XDEBUG_PROFILE=1;path=/;';window.location.reload();})()";
$profilerOff = "javascript:(function(){document.cookie='XDEBUG_PROFILE=;expires=Mon,%2005%20Jul%202000%2000:00:00%20GMT;path=/;';window.location.reload();})()";
?>
<h3>Debug is &laquo;<span
      class="text-<?= Application::getInstance()->isDebug() ? 'danger' : 'success' ?>"><?= Application::getInstance(
        )->isDebug() ? 'ON' : 'OFF' ?></span>&raquo;
</h3>
<section>
  <p class="alert alert-info">
    Bookmark these links to your browser bar for future use (drag'n'drop it)
    <a href="<?= $on ?>" class="btn btn-success span2">Bluz Debug [ON]</a>
    <a href="<?= $off ?>" class="btn btn-danger span2">Bluz Debug [OFF]</a>
  </p>
</section>

<h3>Profiler</h3>
<section>
  <p class="alert alert-info">
    Bookmarklets for XDebug Profiler
    <a href="<?= $profilerOn ?>" class="btn btn-success span2">Profiler [ON]</a>
    <a href="<?= $profilerOff ?>" class="btn btn-danger span2">Profiler [OFF]</a>
  </p>
</section>


<h3><?= __('Example') ?></h3>
<section>
<pre>
debug(['key'=>'value'], 123, new \stdClass());
</pre>
<div>
<?php
debug(['key' => 'value'], 123, new \stdClass());
?>
</div>
</section>
