<h2>Bookmarklets for debug site</h2>
<?php
    // for IDE syntax highlighter
    /** @var $key */
    $on = "javascript:(function(){document.cookie='$key=1;path=/;';window.location.reload();})()";
    $off = "javascript:(function(){document.cookie='$key=;expires=Mon,%2005%20Jul%202000%2000:00:00%20GMT;path=/;';window.location.reload();})()";
?>
<div class="well">
    <h3>Debug is &laquo;<span class="text-<?=DEBUG?'error':'success'?>"><?=DEBUG?'ON':'OFF'?></span>&raquo;</h3>
    <p class="alert alert-info">
        Bookmark these links to your browser bar for future use (drag'n'drop it)
    </p>
    <div class="row">
        <a href="<?= $on ?>" class="btn btn-danger span2">Bluz Debug [ON]</a>
        <a href="<?= $off ?>" class="btn btn-success span2">Bluz Debug [OFF]</a>
    </div>
</div>



<h3>Example</h3>
<pre>
debug(['key'=>'value'], 123, new \stdClass());
</pre>
<h3>Result</h3>
<div class="well">
    <?php
        debug(['key'=>'value'], 123, new \stdClass());
    ?>
</div>
