<?php /* @var \Bluz\View\View $this */ ?>
<ul>
  <li><?= $this->ahref(
          __('Swagger documented API'),
          $this->baseUrl('api-reference') . '/index.html?url=' . Bluz\Proxy\Router::getFullUrl('system', 'api')
      ); ?></li>
  <li><?= $this->ahref(__('Bookmarklets generator'), ['system', 'bookmarks']) ?></li>
  <li><?= $this->ahref(__('Routers Map'), ['system', 'routers']); ?></li>
  <li><?= $this->ahref(__('Load average'), ['system', 'load']); ?></li>
  <li><?= $this->ahref(__('PHP Info'), ['system', 'info']); ?></li>
</ul>