<?php
$one = $load[0] ?? 0;
$five = $load[1] ?? 0;
$fifteen = $load[2] ?? 0;
?>

<table class="table table-responsive table-hover">
  <tr>
    <th width="120" class="text-center"><?= __('Period') ?></th>
    <th width="120" class="text-center"><?= __('Load average') ?></th>
    <th></th>
  </tr>
  <tr class="<?= ($one >= 0.7 ? ($one >= 0.8 ? "danger" : "warning") : "") ?>">
    <th class="text-center"><?= _n('%d minute', '%d minutes', 1, 1) ?></th>
    <td class="text-center"><?= $one ?></td>
    <td></td>
  </tr>
  <tr class="<?= ($five >= 0.7 ? ($five >= 0.8 ? "danger" : "warning") : "") ?>">
    <th class="text-center"><?= _n('%d minute', '%d minutes', 5, 5) ?></th>
    <td class="text-center"><?= $five ?></td>
    <td></td>
  </tr>
  <tr class="<?= ($fifteen >= 0.7 ? ($fifteen >= 0.8 ? "danger" : "warning") : "") ?>">
    <th class="text-center"><?= _n('%d minute', '%d minutes', 15, 15) ?></th>
    <td class="text-center"><?= $fifteen ?></td>
    <td></td>
  </tr>
</table>