<div>
    <table class="table table-striped table-bordered table-condensed table-hover">
        <thead>
            <tr>
                <th width="180px"><?=__('Module')?></th>
                <th width="180px"><?=__('Controller')?></th>
                <th><?=__('Route')?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($routers as $module => $controllers) : ?>
            <tr>
                <th colspan="3"><?=$module?></th>
            </tr>
        <?php foreach ($controllers as $controller => $data) : ?>
            <tr>
                <td>&mdash;</td>
                <td><?=$controller?></td>
                <td><?=join('<br/>', $data['route'])?></td>
            </tr>
        <?php endforeach; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>