<?php
/**
 * @var \Bluz\View\View $this
 */
?>
<?php $uid = uniqid('form_'); ?>
<style>
    #<?=$uid?> .modal {
        /*top: 40%;*/
        width: 750px;
        margin-left: -345px;
        margin-right: -375px;
    }
    #<?=$uid?> .modal-body {
        max-height: 600px;
    }
    #<?=$uid?> textarea {
        margin-left: 100px;
    }
    #<?=$uid?> .redactor_box textarea {
        margin-left: 0;
    }
    @media (max-width: 767px) {
        #<?=$uid?> .modal.modal {
            top: 10px;
            width: 90%;
            margin: 0
        }
    }
</style>
<?=$this->headScript('require(["jquery", "bluz"], function($, bluz) {
    bluz.ready(function(){
        $("#title").blur(function(){
            if ($("#alias").val() == "") {
                var title = $(this).val();
                title = title.toLowerCase();
                title = title.replace(/[ :;]+/gi, "-");
                title = title.replace(/[-]+/gi, "-");
                title = title.replace(/[^a-z0-9.-]/gi, "");
                $("#alias").val(title);
            }
        });
    });
});');
?>
<form id="<?=$uid?>" action="<?=$this->url('pages', 'crud')?>" class="form-horizontal ajax" method="<?=$method?>">
    <input type="hidden" name="data[id]" value="<?=$row->id?>"/>
    <div class="modal">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3>Pages</h3>
    </div>
    <div class="modal-body">
        <div class="control-group">
            <label class="control-label" for="title"><?=$this->__('Title')?>:</label>
            <div class="controls">
                <input type="text" class="input-xlarge" id="title" name="data[title]" value="<?=($row->title)?>" />
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="alias"><?=$this->__('Alias')?>:</label>
            <div class="controls">
                <input type="text" class="input-xlarge" id="alias" name="data[alias]" value="<?=($row->alias)?>" />
            </div>
            <small class="help-block controls">Alias for build permalink to this page</small>
        </div>
        <div class="control-group">
            <label class="control-label" for="keywords"><?=$this->__('Meta Keywords')?>:</label>
            <div class="controls">
                <input type="text" class="input-xlarge" id="keywords" name="data[keywords]" value="<?=($row->keywords)?>" />
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="description"><?=$this->__('Meta Description')?>:</label>
            <div class="controls">
                <input type="text" class="input-xlarge" id="description" name="data[description]" value="<?=($row->description)?>" />
            </div>
        </div>
        <div class="control-group">
            <label for="content" class="control-label"><?=$this->__('Content')?>:</label>
            <br class="clear"/>
            <textarea rows="8" cols="26" id="content" class="input-xxlarge redactor" name="data[content]"><?=($row->content)?></textarea>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary"><?=$this->__('Save')?></button>
        <a href="#" class="btn" data-dismiss="modal"><?=$this->__('Close')?></a>
    </div>
    </div>
</form>

<?php
/*
    echo $this->redactor('.redactor', [
        'autoresize' => false,
        'imageGetJson' => $this->url('media', 'list')
    ])
*/
?>