<?php
/** @var \Bluz\View\View $this */ ?>
<?php
$uid = uniqid('form_', false); ?>
    <form id="<?= $uid ?>" action="<?= $this->url('pages', 'crud') ?>" class="form-horizontal" data-ajax
          method="<?= $method ?>" novalidate>
        <input type="hidden" name="id" value="<?= $row->id ?>"/>
        <input type="hidden" name="_method" value="<?= $method ?>"/>
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><?= __('Edit page') ?></h4>
                <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div class="form-group row mb-1">
                    <label class="col-form-label col-lg-2" for="title"><?= __('Title') ?>:</label>
                    <div class="col-lg-10">
                        <input type="text" class="form-control" id="title" name="title" value="<?= esc($row->title) ?>"
                               required/>
                    </div>
                </div>
                <div class="form-group row mb-1">
                    <label class="col-form-label col-lg-2" for="alias"><?= __('Alias') ?>:</label>
                    <div class="col-lg-10">
                        <input type="text" class="form-control" id="alias" name="alias" value="<?= esc($row->alias) ?>"
                               required/>
                        <small class="help-block controls"><?= __('Alias for build permalink to this page') ?></small>
                    </div>
                </div>
                <div class="form-group row mb-1">
                    <div class="col-lg-12">
                        <label for="content" class="form-control-label"><?= __('Content') ?>:</label>
                        <textarea rows="24" cols="26" id="content" class="form-control redactor" name="content"><?= esc(
                                $row->content
                            ) ?></textarea>
                    </div>
                </div>
                <div class="form-group row mb-1">
                    <div class="col-lg-2"></div>
                    <p class="help-block col-lg-10"><?= __('Meta information about page') ?></p>

                    <label class="col-form-label col-lg-2" for="keywords"><?= __('Keywords') ?>:</label>
                    <div class="col-lg-10">
                        <input type="text" class="form-control" id="keywords" name="keywords"
                               value="<?= esc($row->keywords) ?>"/>
                    </div>
                </div>
                <div class="form-group row mb-1">
                    <label class="col-form-label col-lg-2" for="description"><?= __('Description') ?>:</label>
                    <div class="col-lg-10">
                        <input type="text" class="form-control" id="description" name="description"
                               value="<?= esc($row->description) ?>"/>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary"><?= __('Save') ?></button>
                <button type="button" class="btn btn-light" data-bs-dismiss="modal"><?= __('Close') ?></button>
            </div>
        </div>
    </form>
<?= $this->redactor('.redactor', ['minHeight' => '480px']) ?>
    <script>
        require(['jquery', 'bluz.tools'], function ($, tools) {
            $('#title').blur(function () {
                let $alias = $('#alias');
                if ($alias.val() === '') {
                    let title = $(this).val();
                    title = tools.alias(title);
                    $alias.val(title);
                }
            });
        });
    </script>
<?php
// need for plain request
if (isset($errors)) :
    echo $this->partial('crud/errors.phtml', ['uid' => $uid, 'errors' => $errors]);
endif;
?>