<?php
/**
 * @var \Bluz\View\View $this
 */
?>
<?php $uid = uniqid('form_'); ?>
<form id="<?=$uid?>" action="<?=$this->url('pages', 'crud')?>" class="form-horizontal ajax" method="<?=$method?>">
    <input type="hidden" name="id" value="<?=$row->id?>"/>
    <input type="hidden" name="_method" value="<?=$method?>"/>
    <div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><?=__('Edit page')?></h4>
    </div>
    <div class="modal-body">
        <div class="form-group">
            <label class="control-label col-lg-2" for="title"><?=__('Title')?>:</label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="title" name="title" value="<?=esc($row->title)?>" required />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="alias"><?=__('Alias')?>:</label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="alias" name="alias" value="<?=esc($row->alias)?>" required />
                <small class="help-block controls"><?=__('Alias for build permalink to this page')?></small>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-12">
                <label for="content" class="control-label"><?=__('Content')?>:</label>
                <textarea rows="24" cols="26" id="content" class="form-control redactor" name="content" ><?=esc($row->content)?></textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-2"></div>
            <p class="help-block col-lg-10"><?=__('Meta information about page')?></p>

            <label class="control-label col-lg-2" for="keywords"><?=__('Keywords')?>:</label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="keywords" name="keywords" value="<?=esc($row->keywords)?>" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="description"><?=__('Description')?>:</label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="description" name="description" value="<?=esc($row->description)?>" />
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary"><?=__('Save')?></button>
        <a href="#" class="btn btn-default" data-dismiss="modal"><?=__('Close')?></a>
    </div>
    </div>
</form>
<?= $this->redactor('.redactor', ['minHeight' => 480]) ?>
<script>
    require(['jquery', 'bluz.tools'], function($, tools) {
        $("#title").blur(function() {
            var $alias = $("#alias");
            if ($alias.val() == "") {
                var title = $(this).val();
                title = tools.alias(title);
                $alias.val(title);
            }
        });
    });
</script>
<?php
// need for plain request
if (isset($errors)) :
    $data = json_encode(['errors'=>$errors]);
    $this->headScript('require(["bluz.form"], function(form) {
        form.notices($("#'.$uid.'"), '.$data.');
    });');
endif;
?>