Limit: <a href="<?=$grid->limit(5)?>">5</a>, <a href="<?=$grid->limit(10)?>">10</a>

<table class="table">
    <thead>
        <tr>
            <th><a href="<?=$grid->order('id', null, 'desc', false)?>">Id</a></th>
            <th><a href="<?=$grid->order('name')?>">Name</a></th>
            <th><a href="<?=$grid->order('email')?>">Email</a></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($grid->getData() as $row) : ?>
        <tr>
            <td><?=$row['id']?></td>
            <td><?=$row['name']?></td>
            <td><?=$row['email']?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="2">
                <?php if ($prev = $grid->prev()) : ?><a href="<?=$prev?>">Prev</a> <?php endif; ?>
                <?php if ($next = $grid->next()) : ?><a href="<?=$next?>">Next</a> <?php endif; ?>
            </td>
            <td>
                Total: <strong><?=$grid->total()?></strong> records on <strong><?=$grid->pages()?></strong> pages
            </td>
        </tr>
    </tfoot>
</table>
