<div>
    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <th width="180px">Module</th>
                <th width="180px">Controller</th>
                <th>Route</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($routers as $module => $controllers) : ?>
            <tr>
                <th colspan="3"><?=$module?></th>
            </tr>
        <?php foreach ($controllers as $controller => $data) : ?>
            <tr>
                <td>&mdash;</td>
                <td><?=$controller?></td>
                <td><?=$data['route']?></td>
            </tr>
        <?php endforeach; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>