<?php if ($adapter) : ?>
  <div class="card text-white bg-success mb-3">
    <div class="card-header"><?= __('Cache') ?></div>
    <div class="card-body">
      <h4 class="card-title"><?= __('Cache is enabled') ?></h4>
      <p class="card-text"><?= __('Current cache adapter is %s', $adapter) ?></p>
      <div class="card-body text-dark">
        <div class="list-group">
          <a href="<?= $this->url('cache', 'clean') ?>"
             class="list-group-item list-group-item-warning ajax confirm">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1"><?= __('Clean system data') ?></h5>
              <small><i class="fa fa-fire fa-fw"></i></small>
            </div>
          </a>
          <a href="<?= $this->url('cache', 'flush') ?>"
             class="list-group-item list-group-item-danger ajax confirm">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1"><?= __('Clean all data') ?></h5>
              <small><i class="fa fa-fire fa-fw"></i></small>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
<?php else: ?>
  <div class="card bg-light mb-3">
    <div class="card-header"><?= __('Cache') ?></div>
    <div class="card-body">
      <h4 class="card-title"><?= __('Cache is disabled') ?></h4>
      <p class="card-text">
        <?= __('Read manual for more information') ?><br/>
        <a href="https://github.com/bluzphp/framework/wiki/Cache">wiki/Cache</a>
      </p>
    </div>
  </div>
<?php endif; ?>


