<div class="card-columns" style="-webkit-column-count: 4;-moz-column-count: 4;column-count: 4;">
  <?= $this->dispatch('system', 'widgets/load') ?>
  <?= $this->dispatch('cache', 'widgets/index') ?>
  <?= $this->dispatch('users', 'widgets/stats') ?>
  <?= $this->dispatch('users', 'widgets/card') ?>

  <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
    <div class="card-header">Header</div>
    <div class="card-body">
      <h4 class="card-title">Primary card title</h4>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
  </div>

  <div class="card bg-light mb-3" style="max-width: 20rem;">
    <div class="card-header">Header</div>
    <div class="card-body">
      <h4 class="card-title">Light card title</h4>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
  </div>
  <div class="card text-white bg-dark mb-3" style="max-width: 20rem;">
    <div class="card-header">Header</div>
    <div class="card-body">
      <h4 class="card-title">Dark card title</h4>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
  </div>
</div>