<?php
/* @var \Bluz\View\View $this */
$this->headScript('//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.1/underscore.js');
$this->headScript('//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.0.0/backbone.js');
?>
<script>
    require(['jquery'], function($) {
        $(function(){
            window.Test = Backbone.Model.extend({
                urlRoot: '/test/rest/',
    //            url: function() {
    //                return this.urlRoot;
    //            },
                defaults:{
                    "id":null,
                    "name":"",
                    "email":"",
                    "status":""
                }
            });

            window.TestCollection = Backbone.Collection.extend({
                model:Test,
                url: '/test/rest/'
            });

            var testList = new TestCollection();
            // Listener on all events
            testList.on('all', function(event){
                console.log(event);
            });
            // Load data
            testList.fetch({
                "success":function (collection, response) {
                    console.dir(collection); // collection
                    console.dir(response); // the raw data from the server
                },
                "error":function (collection, response) {
                    alert('Script Error!');
                }
            });
        });
    });
</script>