<?php if (isset($errors)) :?>
<script>
    require(['bluz.form'], function(form) {
        var $form = $('#form');
        <?php foreach ($errors as $field => $error) : ?>
        form.notice($form, '[name^="<?=$field?>"]', '<?=$error?>');
        <?php endforeach;?>
    });
</script>
<?php endif; ?>
<form id="form" action="<?=$this->url('test', 'create')?>" class="form-horizontal" method="POST">
    <div class="form-group">
        <label class="control-label col-lg-2" for="inputName">Name</label>
        <div class="col-lg-10">
            <input type="text" id="inputName" name="name" placeholder="" value="<?=$row->name?>" class="form-control"/>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-lg-2" for="inputEmail">Email</label>
        <div class="col-lg-10">
            <input type="text" id="inputEmail" name="email" placeholder="example@domain.com" value="<?=$row->email?>" class="form-control"/>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-lg-2" for="inputStatus">Status</label>
        <div class="col-lg-10">
            <?php
                $statuses = ['', 'active', 'delete', 'disable'];
            ?>
            <?=$this->select('status', array_combine($statuses, $statuses), $row->status, ['class'=>'form-control'])?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-10 col-offset-2">
            <button type="submit" class="btn btn-primary"><?=__('Save')?></button>
        </div>
    </div>
</form>