<?php $uid = uniqid('form_'); ?>
<form id="<?=$uid?>" action="<?=$this->url('test', 'crud')?>" class="form-horizontal ajax" method="<?=$method?>">
    <input type="hidden" name="id" value="<?=$row->id?>"/>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title">Test Table</h3>
    </div>
    <div class="modal-body">
        <div class="form-group">
            <label class="control-label col-lg-2" for="name"><?=__('Name')?></label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="name" name="name" value="<?=($row->name)?>" required />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="email"><?=__('Email')?></label>
            <div class="col-lg-10">
                <input type="email" class="form-control" id="email" name="email" value="<?=($row->email)?>" required />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="status"><?=__('Status')?></label>
            <div class="col-lg-10">
                <select id="status" name="status" class="form-control">
                    <option <?=$row->status=='active'?'selected':''?>>active</option>
                    <option <?=$row->status=='disable'?'selected':''?>>disable</option>
                    <option <?=$row->status=='delete'?'selected':''?>>delete</option>
                </select>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary"><?=__('Save')?></button>
        <a href="#" class="btn btn-default" data-dismiss="modal"><?=__('Close')?></a>
    </div>
</form>

<?php
if (isset($errors)) :
    $data = json_encode(['errors'=>$errors]);
    $this->headScript('require(["bluz.form"], function(form) {
        form.notices($("#'.$uid.'"), '.$data.');
    });');
endif;
?>
