<?php
use Application\Test;
use Bluz\Proxy\Db;

?>
<h3>Example of usage DB methods</h3>
<p class="text-warning">Please, never use <code>DB</code> adapter inside <code>View</code></p>

<h4><code>Db::fetchOne("SELECT count(*) FROM test LIMIT 1")</code></h4>
<?php
$res = Db::fetchOne("SELECT count(*) FROM test LIMIT 1");
var_dump($res);
?>

<h4><code>Db::fetchRow("SELECT * FROM test WHERE name LIKE ?", ["al%"])</code></h4>
<?php
$res = Db::fetchRow("SELECT * FROM test WHERE name LIKE ?", ["al%"]);
var_dump($res);
?>

<h4><code>Db::fetchAll("SELECT * FROM test WHERE name LIKE ? LIMIT 10", ["al%"])</code></h4>
<?php
$res = Db::fetchAll("SELECT * FROM test WHERE name LIKE ? LIMIT 10", ["al%"]);
var_dump($res);
?>

<h4><code>Db::fetchColumn("SELECT name FROM test WHERE name LIKE ? LIMIT 10", ["al%"])</code></h4>
<?php
$res = Db::fetchColumn("SELECT name FROM test WHERE name LIKE ? LIMIT 10", ["al%"]);
var_dump($res);

?>

<h4><code>Db::fetchPairs("SELECT name, id FROM test LIMIT 10")</code></h4>
<?php
$res = Db::fetchPairs("SELECT name, id FROM test LIMIT 10");
var_dump($res);

?>

<h4><code>Db::fetchGroup("SELECT name, id FROM test LIMIT 10")</code></h4>
<?php
$res = Db::fetchGroup("SELECT name, id FROM test LIMIT 10");
var_dump($res);
?>

<h4><code>Db::fetchColumnGroup("SELECT name, id FROM test LIMIT 10")</code></h4>
<?php
$res = Db::fetchColumnGroup("SELECT name, id FROM test LIMIT 10");
var_dump($res);
?>

<h4><code>Db::fetchObject("SELECT * FROM test LIMIT 1")</code></h4>
<?php
$res = Db::fetchObject("SELECT * FROM test LIMIT 1");
var_dump($res);
?>

<h4><code>Db::fetchObject("SELECT * FROM test LIMIT 1", [], "\\Application\\Test\\Row")</code></h4>
<?php
$res = Db::fetchObject("SELECT * FROM test LIMIT 1", [], "\\Application\\Test\\Row");
var_dump($res);
?>

<h4><code>Db::fetchObject("SELECT * FROM test LIMIT 1", [], new Test\Row())</code></h4>
<?php
$res = Db::fetchObject("SELECT * FROM test LIMIT 1", [], new Test\Row());
var_dump($res);
?>