<h3>Form Example</h3>
<form action="" method="post">
    <div class="form-group">
        <label>Number: <input type="number" class="form-control" name="int" value="1"/></label>
    </div>

    <div class="form-group">
        <label>String:
        <input type="text" class="form-control" name="string" placeholder="..." value="Lorem ipsum...">
        </label>
    </div>

    <div class="form-group">
        <label>Array:
        <input type="text" class="form-control" name="array[2]" placeholder="1" value="1">
        <input type="text" class="form-control" name="array[]" placeholder="2" value="2">
        <input type="text" class="form-control" name="array[]" placeholder="3" value="3">
        </label>
    </div>

    <div class="checkbox">
        <label>
            Optional:
            <input type="checkbox" name="optional" value="1"> Check me out
        </label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

<?php if (isset($params)) : ?>
<h2>Request result</h2>
<hr/>
<?=$inside?>
<hr/>
<?php var_dump($params) ?>
<?php endif;?>