<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
if (!$grid) return;
?>
<div class="clearfix" data-spy="grid" data-grid="<?=$grid->getUid()?>">
    <script>
        // use data-spy="grid" for use AJAX for reload grid
        require(['bluz.grid']);
    </script>
    <p>
        Filters:<br/>
        <a href="<?=$grid->filter('id', 'gt', 3)?>">Id &gt; 3</a> <br/>
        <a href="<?=$grid->filter('id', 'lt', 9)?>">Id &lt; 9</a> <br/>
        <a href="<?=$grid->filter('id', 'ne', 5, false)?>">AND Id != 5</a>
    </p>

    <?= $this->partial('grid/total.phtml', ['grid'=>$grid]) ?>
    <?= $this->partial('grid/limit.phtml', ['grid'=>$grid]) ?>

    <table class="table grid">
        <thead>
            <tr>
                <th width="40px"><a href="<?=$grid->order('id', null, 'desc', false)?>">Id</a></th>
                <th><a href="<?=$grid->order('name')?>">Name</a></th>
                <th><a href="<?=$grid->order('email')?>">Email</a></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($grid->getData() as $row) : ?>
            <tr>
                <td><?=$row['id']?></td>
                <td><?=$row['name']?></td>
                <td><?=$row['email']?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?= $this->partial('grid/empty-rows.phtml', ['grid'=>$grid]) ?>
    <?= $this->partial('grid/pagination.phtml', ['grid'=>$grid]) ?>
    <?= $this->partial('grid/total.phtml', ['grid'=>$grid]) ?>

</div>