<ul>
    <li><?= $this->ahref('Bootstrap Controls', ['test', 'controls']) ?></li>
    <li><?= $this->ahref('Bootstrap Markup', ['test', 'markup']);?></li>
    <li><?= $this->ahref('Cache View', ['test', 'cache-view']);?></li>
    <li><?= $this->ahref('Cache Data', ['test', 'cache-data', ['id'=>1]]);?></li>
    <li><?= $this->ahref('Controller &rarr; Closure', ['test', 'closure']);?></li>
    <li><?= $this->ahref('Controller &rarr; No View', ['test', 'no-view']);?></li>
    <li><?= $this->ahref('Events', ['test', 'events']);?></li>
    <li><?= $this->ahref('Grid [Array]', ['test', 'array-grid']);?></li>
    <li><?= $this->ahref('Grid [SQL]', ['test', 'sql-grid']);?></li>
    <li><?= $this->ahref('Partial', ['test', 'partial']);?></li>
    <li><?= $this->ahref('Routers', ['test', 'route']);?></li>
    <li><?= $this->ahref('Session', ['test', 'session']);?></li>
</ul>
<hr/>
<div class="btn-group">
    <?= $this->ahref('Ajax GET', ['test', 'ajax'], ['class'=>'ajax btn', 'data-ajax-method'=>'GET']);?>
    <?= $this->ahref('Ajax POST', ['test', 'ajax'], ['class'=>'ajax btn', 'data-ajax-method'=>'POST']);?>
    <?= $this->ahref('Ajax PUT', ['test', 'ajax'], ['class'=>'ajax btn', 'data-ajax-method'=>'PUT']);?>
    <?= $this->ahref('Ajax DELETE', ['test', 'ajax'], ['class'=>'ajax btn', 'data-ajax-method'=>'DELETE']);?>
</div>
<hr/>
<div class="btn-group">
    <?= $this->ahref('Ajax + Messages', ['test', 'ajax'], ['class'=>'ajax btn', 'data-messages'=>true]);?>
    <?= $this->ahref('Ajax + Alert', ['test', 'ajax-callback'], ['class'=>'ajax btn btn-primary']);?>
    <?= $this->ahref('Ajax + Confirm', ['test', 'ajax'], ['class'=>'ajax confirm btn btn-danger']);?>
    <?= $this->ahref('Loading', ['test', 'ajax-html'], ['class'=>'load btn', 'data-ajax-target'=>'#load']);?>
    <?= $this->ahref('Confirm', ['index', 'index'], ['class'=>'confirm btn', 'data-confirm'=>'Confirm?']);?>
</div>
<hr/>
<div id="load">
    <?= $this->dispatch('test', 'closure') ?>
</div>