<?php
/**
 * @var \Application\Users\Row $user
 * @var \Bluz\View\View $this
 */
?>

<h3>Hello, <?=$this->username()?></h3>
<p>This is page consist many examples, all of them you can find in test module</p>
<h3>Controller features</h3>
<ul>
    <li><?= $this->ahref('Reflection Data', ['test', 'reflection']);?></li>
    <li><?= $this->ahref('Controller &rarr; Disable View', ['test', 'no-view']);?></li>
    <li><?= $this->ahref('Controller &rarr; Disable Output', ['test', 'no-output']);?></li>
</ul>
<hr/>
<ul>
    <li><?= $this->ahref('CRUD', ['test', 'grid-sql']) ?> &mdash; Create, Read, Update and Delete examples</li>
    <li><?= $this->ahref('REST + Backbone', ['test', 'backbone']) ?> &mdash; is working</li>
    <li><?= $this->ahref('REST + React', ['test', 'react']) ?> &mdash; is working too</li>
</ul>
<hr/>
<ul>
    <li><?= $this->ahref('Download File', ['test', 'file']) ?> &mdash; Send file to browser</li>
    <li><?= $this->ahref('Cookies', ['test', 'cookies']) ?> &mdash; Send cookies to browser</li>
</ul>
<hr/>
<p>Try REST methods</p>
<div id="rest">
    <div class="btn-group">
        <?= $this->ahref('GET 10 Records', ['test', 'rest'], ['class'=>'ajax btn btn-default', 'data-ajax-method'=>'GET', 'id'=> 'rest-get']);?>
        <?= $this->ahref('HEAD 10 Records', ['test', 'rest'], ['class'=>'ajax btn btn-default', 'data-ajax-method'=>'HEAD']);?>
    </div>
    <br/>
    <br/>
    <div class="btn-group">
        <?= $this->ahref('GET Record ID:10', 'test/rest/10', ['class'=>'ajax btn btn-default', 'data-ajax-method'=>'GET']);?>
        <?= $this->ahref('HEAD Record ID:10', 'test/rest/10', ['class'=>'ajax btn btn-default', 'data-ajax-method'=>'HEAD']);?>
    </div>
    <br/>
    <br/>
    <div class="btn-group">
        <?= $this->ahref('<span class="badge">1</span> POST Create Record', ['test', 'rest-post'], ['class'=>'ajax btn btn-primary', 'data-ajax-method'=>'POST', 'data-name'=> 'Name', 'data-email'=> 'email@bluz.com']);?>
        <?= $this->ahref('<span class="badge">2</span> PUT Edit Record', 'test/rest-put/10', ['class'=>'ajax btn btn-success', 'data-ajax-method'=>'PUT', 'data-name'=> 'New Name']);?>
        <?= $this->ahref('<span class="badge">3</span> DELETE Record', 'test/rest-delete/10', ['class'=>'ajax btn btn-danger', 'data-ajax-method'=>'DELETE']);?>
    </div>
</div>
<script>
    require(["jquery", "bluz.notify"], function($, notify) {
        $(function(){
            $('#rest')
                .on('success.ajax.bluz', function(event, data, textStatus, jqXHR){
                    console.log(data);

                    // check correct creation
                    if (jqXHR.getResponseHeader('Location')) {
                        var partial = jqXHR.getResponseHeader('Location').split('/');
                        $('#rest a[data-ajax-method=PUT]').attr('href', 'test/rest-put/'+partial[3]);
                        $('#rest a[data-ajax-method=DELETE]').attr('href', 'test/rest-delete/'+partial[3]);
                    }

                    notify.addSuccess("OK. Additional information in console")
                })
                .on('error.ajax.bluz', function(event, jqXHR, textStatus, errorThrown){

                });
        });
    });
</script>

<h3>CLI</h3>
<p>
For test CLI you can run <code>`php ./bin/cli.php --uri 'test/cli' --env='dev'`</code>.
You can find source code at <code>`application/modules/test/controllers/cli.php`</code>
</p>

<h3>Packages</h3>
<ul>
    <li><?= $this->ahref('Cache Controller', ['test', 'cache-controller']);?></li>
    <li><?= $this->ahref('Cache Data', ['test', 'cache-data', ['id'=>1]]);?></li>
    <li><?= $this->ahref('DB Operations', ['test', 'db']);?></li>
    <li><?= $this->ahref('DB Query Builders', ['test', 'db-query']);?></li>
    <li><?= $this->ahref('DB Relations', ['test', 'db-relations']);?></li>
    <li><?= $this->ahref('DB Table', ['test', 'db-table']);?></li>
    <li><?= $this->ahref('Events', ['test', 'events']);?></li>
    <li><?= $this->ahref('Request', ['test', 'request']);?></li>
    <li><?= $this->ahref('Routers', ['test', 'route']);?></li>
    <li><?= $this->ahref('Session', ['test', 'session']);?></li>
    <li><?= $this->ahref('Grid with Array source', ['test', 'grid-array']);?></li>
    <li><?= $this->ahref('Grid with Select source', ['test', 'grid-select']);?></li>
    <li><?= $this->ahref('Grid with Table source', ['test', 'grid-table']);?></li>
    <li><?= $this->ahref('Grid with SQL source', ['test', 'grid-sql']);?></li>
    <li><?= $this->ahref('Grid with custom route', ['test', 'grid-route', ['alias'=>'example']]);?></li>
    <li><?= $this->ahref('Grid with filter search', ['test', 'grid-with-filter']);?></li>
    <li><?= $this->ahref('Mailer', ['test', 'mailer']);?></li>
    <li><?= $this->ahref('View Partials', ['test', 'view-partial']);?></li>
    <li><?= $this->ahref('View Form Helpers', ['test', 'view-helpers']);?></li>
</ul>
<hr/>
<ul>
    <li><?= $this->ahref('Options', ['test', 'options']) ?> &mdash; example of usage module Options from another module</li>
</ul>
<hr/>

<h3>Magic AJAX calls</h3>
<p>Try AJAX calls over GET/POST/PUT/DELTE HTTPs methods</p>
<div class="btn-group">
    <?= $this->ahref('GET', ['test', 'ajax'], ['class'=>'ajax btn btn-default', 'data-ajax-method'=>'GET']);?>
    <?= $this->ahref('POST', ['test', 'ajax'], ['class'=>'ajax btn btn-default', 'data-ajax-method'=>'POST']);?>
    <?= $this->ahref('PUT', ['test', 'ajax'], ['class'=>'ajax btn btn-default', 'data-ajax-method'=>'PUT']);?>
    <?= $this->ahref('DELETE', ['test', 'ajax'], ['class'=>'ajax btn btn-default', 'data-ajax-method'=>'DELETE']);?>
</div>
<hr/>
<div class="btn-group">
    <a href="<?= $this->url('test', 'ajax') ?>" id="ajax-callback" class="btn btn-default ajax">AJAX call with fired trigger</a>
</div>
<hr/>
<p>Example of JavaScript:</p>
<pre>
    require(["jquery", "bluz.notify"], function($, notify) {
        $(function(){
            $('#ajax-callback')
                .on('success.ajax.bluz', function(event, data, textStatus, jqXHR){
                    notify.addSuccess("Event `success.ajax.bluz` is fired")
                })
                .on('error.ajax.bluz', function(event, jqXHR, textStatus, errorThrown){
                    notify.addSuccess("Event `error.ajax.bluz` is fired")
                });
        });
    });
</pre>
<script>
    require(["jquery", "bluz.notify"], function($, notify) {
        $(function(){
            $('#ajax-callback')
                .on('success.ajax.bluz', function(event, data, textStatus, jqXHR){
                    notify.addSuccess("Event `success.ajax.bluz` is fired")
                })
                .on('error.ajax.bluz', function(event, jqXHR, textStatus, errorThrown){
                    notify.addSuccess("Event `error.ajax.bluz` is fired")
                });
        });
    });
</script>
<hr/>
<div class="btn-group">
    <?= $this->ahref('Ajax + Messages', ['test', 'ajax'], ['class'=>'ajax btn btn-default', 'data-messages'=>true]);?>
    <?= $this->ahref('Ajax + Confirm', ['test', 'ajax'], ['class'=>'ajax confirm btn btn-danger']);?>
    <?= $this->ahref('Loading', ['test', 'ajax-html'], ['class'=>'load btn btn-default', 'data-ajax-target'=>'#load']);?>
    <?= $this->ahref('Confirm', ['index', 'index'], ['class'=>'confirm btn btn-default', 'data-confirm'=>'Confirm?']);?>
</div>

<div id="load">
    <h3>Loading to this container</h3>
</div>

<hr/>

<div class="row">
    <div class="col-md-3 form-group">
        <select class="form-control load" name="formName" data-ajax-source="/test/ajax-form"
                data-ajax-target="#formPlace">
            <option value="">Select Form</option>
            <option value="first-form">First</option>
            <option value="second-form">Second</option>
        </select>
    </div>
</div>

<div class="row">
    <div id="formPlace">
        <h3>Form loading to this container</h3>
    </div>
</div>

<hr/>

<h3>Access denied</h3>
<div class="btn-group">
    <a href="<?= $this->url('test', 'denied') ?>" class="btn btn-default bluz-tooltip ajax" data-toggle="tooltip" title="Return error message">Denied page, AJAX call</a>
    <a href="<?= $this->url('test', 'denied') ?>" class="btn btn-default bluz-tooltip dialog" data-toggle="tooltip" title="Return error dialog">Denied page, dialog</a>
</div>
<hr/>

<h3>Exceptions</h3>
<ul>
    <li><?= $this->ahref('Throw exception from controller', ['test', 'exception']) ?></li>
    <li><?= $this->ahref('Throw exception from view', ['test', 'exception-view']) ?></li>
</ul>
<hr/>

<h3>Dispatch controller</h3>
<pre>
$this->dispatch('test', 'empty')
</pre>
<div>
    <?= $this->dispatch('test', 'empty') ?>
</div>

<h3>Dispatch controller with <code>echo</code> call</h3>
<pre>
$this->dispatch('test', 'widgets/lorem')
</pre>
<div>
    <?php $this->dispatch('test', 'widgets/lorem') ?>
</div>

<h3>Wrong controller</h3>
<pre>
$this->dispatch('test', 'not-found')
</pre>
<div>
    <?= $this->dispatch('test', 'not-found') ?>
</div>

<h3>Wrong without privileges</h3>
<pre>
$this->dispatch('test', 'denied')
</pre>
<div>
    <?= $this->dispatch('test', 'denied') ?>
</div>

<h3>Dispatch grid based on array</h3>
<pre>
$this->dispatch('test', 'grid-array')
</pre>
<div>
    <?= $this->dispatch('test', 'grid-array') ?>
</div>

<h3>Dispatch grid based on SQL</h3>
<pre>
$this->dispatch('test', 'grid-sql')
</pre>
<div>
    <?= $this->dispatch('test', 'grid-sql') ?>
</div>