<p>Send &laquo;Hello!&raquo; e-mail message to</p>
<form action="/test/mailer/" method="POST">
    <div class="control-group">
        <label class="input-prepend">
            <span class="add-on"><i class="icon-envelope"></i></span>
            <input type="text" class="input-large" name="email" value="<?=$email?>" placeholder="<?=$this->__('email')?>"/>
        </label>
    </div>

    <button type="submit" class="btn btn-primary"><?=$this->__('Send')?></button>
</form>