<?php use Bluz\Proxy\Request; ?>

<h3>Proxy\Request Methods</h3>

<h4><code>getMethod()</code></h4>
<code><?php var_dump(Request::getMethod())?></code>

<h4><code>isCli()</code></h4>
<code><?php var_dump(Request::isCli())?></code>

<h4><code>getUri()</code></h4>
<code><?php var_dump(Request::getUri()->__toString())?></code>

<h4><code>getClientIp()</code></h4>
<code><?php var_dump(Request::getClientIp())?></code>
