<h3>Http\Request Methods</h3>

<h4><code>getRequestUri()</code></h4>
<code><?php var_dump(app()->getRequest()->getRequestUri())?></code>

<h4><code>getBaseUrl()</code></h4>
<code><?php var_dump(app()->getRequest()->getBaseUrl())?></code>

<h4><code>getCleanUri()</code></h4>
<code><?php var_dump(app()->getRequest()->getCleanUri())?></code>

<h4><code>getClientIp()</code></h4>
<code><?php var_dump(app()->getRequest()->getClientIp())?></code>
