<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
?>
<script>
    // use data-spy="grid" for use AJAX for reload grid
    require(['bluz.grid']);
</script>

<div data-spy="grid" data-grid="<?=$grid->getUid()?>">
    <p>
        Filters:<br/>
        <a href="<?=$grid->filter('id', 'gt', 30)?>">Id &gt; 30</a> <br/>
        <a href="<?=$grid->filter('id', 'lt', 70)?>">Id &lt; 70</a> <br/>
        <a href="<?=$grid->filter('id', 'ne', 5, false)?>">AND Id != 5</a> <br/>
        <a href="<?=$grid->filter('status', 'eq', 'active')?>">All Active Users</a> <br/>
        <a href="<?=$grid->filter('status', 'eq', 'active', false)?>">AND Active Users</a> <br/>
    </p>
    <div class="input-group">
        <a href="<?=$this->url('test', 'crud')?>" class="btn btn-primary left dialog" data-ajax-method="get">Create</a>
    </div>
    <?php $this->partial('grid/total.phtml', ['grid'=>$grid]) ?>
    <?php $this->partial('grid/limit.phtml', ['grid'=>$grid]) ?>

    <table class="table grid">
        <thead>
            <tr>
                <th width="40px"><a href="<?=$grid->order('id')?:'#'?>">Id</a></th>
                <th><a href="<?=$grid->order('name')?:'#'?>">Name</a></th>
                <th><a href="<?=$grid->order('status')?:'#'?>">Status</a></th>
                <th width="120px"></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($grid->getData() as $row) : ?>
            <tr>
                <td><?=$row['id']?></td>
                <td><?=$row['name']?></td>
                <td><?=$row['status']?></td>
                <td class="controls">
                    <a href="<?=$this->url('test', 'crud', ['data' => ['id' => $row['id']]]);?>" class="btn btn-small btn-primary dialog" data-ajax-method="get">
                        <i class="glyphicon glyphicon-pencil"></i>
                    </a>
                    <a href="<?=$this->url('test', 'crud', ['data' => ['id' => $row['id']]]);?>" class="confirm btn btn-small btn-danger ajax" data-ajax-method="delete">
                        <i class="glyphicon glyphicon-remove"></i>
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php $this->partial('grid/empty-rows.phtml', ['grid'=>$grid]) ?>
    <?php $this->partial('grid/pagination.phtml', ['grid'=>$grid]) ?>
    <?php $this->partial('grid/total.phtml', ['grid'=>$grid]) ?>

</div>
