<script>
    $(function(){
        $('#<?=$grid->getPrefix()?>grid').on('click.bluz.ajax', '.pagination a, thead a', function(){
            var $this = $(this);
            var href = $this.attr('href');

            if (href == '#') return false;

            $.ajax({
                url: href,
                type: 'get',
                dataType:'html',
                beforeSend:function() {
                    $this.addClass('disabled');
                },
                success:function(html) {
                    $('#<?=$grid->getPrefix()?>grid').replaceWith(html);
                }
            });
            return false;
        });
    });
</script>

<div id="<?=$grid->getPrefix()?>grid">
    <a href="<?=$this->url('test', 'crud')?>" class="btn dialog" data-ajax-method="get">Create</a>
    <p>
        Filters:<br/>
        <a href="<?=$grid->filter('id', 'gt', 30)?>">Id &gt; 30</a> <br/>
        <a href="<?=$grid->filter('id', 'lt', 70)?>">Id &lt; 70</a> <br/>
        <a href="<?=$grid->filter('id', 'ne', 5, false)?>">AND Id != 5</a> <br/>
        <a href="<?=$grid->filter('status', 'eq', 'active')?>">All Active Users</a> <br/>
        <a href="<?=$grid->filter('status', 'eq', 'active', false)?>">AND Active Users</a> <br/>
    </p>

    <div class="pagination pagination-right">
        <ul>
            <li><a href="#">Limit</a></li>
            <li <?=(($grid->getLimit()==5)?'class="active"':'')?>><a href="<?=$grid->limit(5)?>">5</a></li>
            <li <?=(($grid->getLimit()==10)?'class="active"':'')?>><a href="<?=$grid->limit(10)?>">10</a></li>
        </ul>
    </div>

    <table class="table grid">
        <thead>
            <tr>
                <th width="40px"><a href="<?=$grid->order('id')?:'#'?>">Id</a></th>
                <th><a href="<?=$grid->order('name')?:'#'?>">Name</a></th>
                <th><a href="<?=$grid->order('status')?:'#'?>">Status</a></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($grid->getData() as $row) : ?>
            <tr>
                <td><?=$row['id']?></td>
                <td><?=$row['name']?></td>
                <td><?=$row['status']?></td>
                <td class="controls"><a href="<?=$this->url('test', 'crud', ['data' => ['id' => $row['id']]]);?>" class="btn dialog" data-ajax-method="get">Edit</a></td>
                <td class="controls"><a href="<?=$this->url('test', 'crud', ['data' => ['id' => $row['id']]]);?>" class="confirm btn btn-danger ajax" data-ajax-method="delete">Delete</a></td>
            </tr>
            <?php endforeach; ?>
            <?php if (sizeof($grid->getData()) < $grid->getLimit()) :
                $emptyRows = $grid->getLimit() - sizeof($grid->getData()); ?>
                <?php for ($i = 0; $i < $emptyRows; $i++): ?>
                <tr>
                    <td colspan="5">&nbsp;</td>
                </tr>
                <?php endfor; ?>
            <?php endif; ?>
        </tbody>
    </table>
    <div class="pagination">
        <?php if ($grid->pages() > 1) : ?>
        <ul>
            <?php if ($prev = $grid->prev()) : ?><li><a href="<?=$prev?>">&laquo;</a></li>
            <?php else : ?> <li class="disabled"><a href="#" onclick="javascript: return false;">&laquo;</a></li>
            <?php endif; ?>


            <?php for ($page = 1; $page <= $grid->pages(); $page++) : ?>
            <li <?=($page==$grid->getPage()?'class="active"':'') ?>><a href="<?=$grid->page($page)?>"><?=$page?></a></li>
            <?php endfor; ?>

            <?php if ($next = $grid->next()) : ?><li><a href="<?=$next?>">&raquo;</a></li>
            <?php else : ?> <li class="disabled"><a href="#" onclick="javascript: return false;">&raquo;</a></li>
            <?php endif; ?>
        </ul>
        <?php endif; ?>

        <ul class="right">
            <li>
                <a href="<?=$grid->reset()?>">Total:
                    <strong><?=$grid->total()?></strong> <?=$this->__('record','records', $grid->total())?> on
                    <strong><?=$grid->pages()?></strong> <?=$this->__('page','pages', $grid->pages())?></a>
            </li>
        </ul>
    </div>

</div>
