<form class="form-horizontal">
    <div class="control-group">
        <label class="control-label" for="inputEmail">Sex</label>
        <div class="controls">
            <label><?=$this->radio('sex', 'male', $sex)?> Male</label>
            <label><?=$this->radio('sex', 'female', $sex)?> Female</label>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="car">Car</label>
        <div class="controls">
            <?=
            $this->select("car", [
                "none" => "No Car",
                "class-A" => [
                    'citroen-c1' => 'Citroen C1',
                    'mercedes-benz-a200' => 'Mercedes Benz A200',
                ],
                "class-B" => [
                    'audi-a1' => 'Audi A1',
                    'citroen-c3' => 'Citroen C3',
                ],
            ], $car, ["id" => "car"]);
            ?>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <label class="checkbox">
                <?=$this->checkbox('remember', true, $remember)?> Remember me
            </label>
            <button type="submit" class="btn"><?=__('Send')?></button>
        </div>
    </div>
</form>