<h3>Form Helpers Example</h3>
<form class="form-horizontal" method="post">
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10">
            <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Sex</label>
        <div class="col-sm-10">
            <div class="radio">
                <label><?=$this->radio('sex', 'male', $sex)?> Male</label>
            </div>
            <div class="radio">
                <label><?=$this->radio('sex', 'female', $sex)?> Female</label>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label" for="car">Car</label>
        <div class="col-sm-10 controls">
            <?=
            $this->select("car", [
                "none" => "No Car",
                "class-A" => [
                    'citroen-c1' => 'Citroen C1',
                    'mercedes-benz-a200' => 'Mercedes Benz A200',
                ],
                "class-B" => [
                    'audi-a1' => 'Audi A1',
                    'citroen-c3' => 'Citroen C3',
                ],
            ], $car, ["id" => "car", "class" => "form-control"]);
            ?>
        </div>
    </div>
    <div class="checkbox col-sm-offset-2">
        <label class="checkbox">
            <?=$this->checkbox('remember', true, $remember)?> Remember me
        </label>
    </div>
    <button type="submit" class="btn btn-primary col-sm-offset-2"><?=__('Send')?></button>
</form>
<?php if (isset($params)) : ?>
<h3>Request result</h3>
<hr/>
<?php var_dump($params) ?>
<?php endif;?>