<form class="form-horizontal">
    <div class="form-group">
        <span class="control-label">Sex</span>
        <div class="radio"><label><?=$this->radio('sex', 'male', $sex)?> Male</label></div>
        <div class="radio"><label><?=$this->radio('sex', 'female', $sex)?> Female</label></div>
    </div>
    <div class="form-group">
        <label class="control-label" for="car">Car</label>
        <div class="controls">
            <?=
            $this->select("car", [
                "none" => "No Car",
                "class-A" => [
                    'citroen-c1' => 'Citroen C1',
                    'mercedes-benz-a200' => 'Mercedes Benz A200',
                ],
                "class-B" => [
                    'audi-a1' => 'Audi A1',
                    'citroen-c3' => 'Citroen C3',
                ],
            ], $car, ["id" => "car", "class" => "form-control"]);
            ?>
        </div>
    </div>
    <div class="form-group">
        <div class="checkbox">
            <label class="checkbox">
                <?=$this->checkbox('remember', true, $remember)?> Remember me
            </label>
        </div>
        <button type="submit" class="btn btn-default"><?=__('Send')?></button>
    </div>
</form>