<?php
/**
 * @var \Bluz\View\View $this
 */
?>
<script>
    // use data-spy="grid" for use AJAX for reload grid
    require(['bluz.categories']);
</script>
<style>
    .tree-wrapper > div {
        margin-bottom: 0;
        font-weight: 700;
    }
    ol.tree, ol.tree ol {
        margin: 0 0 0 25px;
        padding: 0;
        list-style-type: none;
    }
    .tree li {
        margin: 5px 0 0 0;
        padding: 0;
    }
    .tree li div {
        margin: 0;
    }
</style>

<div class="category-page-wrapper">
    <nav class="navbar navbar-default" role="navigation">
        <div class="form-group">
            <div class="col-lg-10">
                <form action="" class="form-horizontal select-tree">
                    <div class="col-sm-2 control-label">
                        <label for="root" class="control-label"><?=__('Module')?></label>
                    </div>
                    <div class="col-sm-10">
                        <select id="root" class="form-control root-category-list">
                            <?php foreach ($rootTree as $tree) { ?>
                                <option value="<?php echo $tree->id ?>"><?php echo $tree->name ?></option>
                            <?php }?>
                        </select>
                    </div>
                </form>
            </div>
            <div class="col-lg-2">
                <a href="<?= $this->url('categories', 'crud') ?>"
                   class="btn btn-primary navbar-btn dialog"
                   data-ajax-method="get"><?=__('Create')?></a>
            </div>
        </div>
    </nav>

    <div class="tree-container">
        <div class="tree-wrapper">
            <?php if ($category) : ?>
                <?= $this->partial('partial/tree.phtml', ['category' => $category]) ?>
            <?php endif; ?>
        </div>
    </div>
</div>