<?php /** @var \Bluz\Layout\Layout $this */ ?>
<?php $this->headStyle($this->baseUrl('css/dashboard.css')); ?>
<?php require 'partial/header.phtml'; ?>
<?php require 'partial/nav-bar.phtml'; ?>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="nav-dashboard" data-spy="affix" data-offset-top="60">
                    <ul class="nav nav-tabs nav-stacked" >
                        <li <?=($this->module('pages')?'class="active"':'')?>><?= $this->ahref('<i class="fa fa-edit fa-fw"></i> '.__('Pages'), ['pages', 'grid', [], true]) ?></li>
                        <li <?=($this->module('users')?'class="active"':'')?>><?= $this->ahref('<i class="fa fa-user fa-fw"></i> '.__('Users'), ['users', 'grid', [], true]) ?></li>
                        <li <?=($this->module('media')?'class="active"':'')?>><?= $this->ahref('<i class="fa fa-picture-o fa-fw"></i> '.__('Media'), ['media', 'grid', [], true]) ?></li>
                        <li <?=($this->module('categories')?'class="active"':'')?>><?= $this->ahref('<i class="fa fa-folder-o fa-fw"></i> '.__('Categories'), ['categories', 'tree', [], true]) ?></li>
                    </ul>
                    <ul class="nav nav-tabs nav-stacked">
                        <li <?=($this->module('acl')?'class="active"':'')?>><?= $this->ahref('<i class="fa fa-lock fa-fw"></i> '.__('Permissions'), ['acl', 'index', [], true]) ?></li>
                        <li <?=($this->module('options')?'class="active"':'')?>><?= $this->ahref('<i class="fa fa-th-list fa-fw"></i> '.__('Options'), ['options', 'grid', [], true]) ?></li>
                    </ul>
                    <ul class="nav nav-tabs nav-stacked">
                        <li <?=($this->module('cache')?'class="active"':'')?>><?= $this->ahref('<i class="fa fa-hdd-o fa-fw"></i> '.__('Cache'), ['cache', 'index', [], true]) ?></li>
                        <li <?=($this->module('system')?'class="active"':'')?>><?= $this->ahref('<i class="fa fa-wrench fa-fw"></i> '.__('System'), ['system', 'index', [], true]) ?></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-9">
                <ul class="breadcrumb">
                    <li>
                        <a href="/" class="bluz-tooltip" data-placement="bottom" data-original-title="<?=__('Back to homepage')?>">
                            <i class="fa fa-home fa-fw"></i>
                            <?=__('Home')?>
                        </a>
                    </li>
                    <?php if ($this->breadCrumbs()) foreach ($this->breadCrumbs() as $crump):?>
                        <li>
                            <?php echo $crump?>
                        </li>
                    <?php endforeach;?>
                </ul>
                <?php
                /* @var closure $content */
                echo $this->getContent();
                ?>
            </div>
        </div>
    </div>
<?php require 'partial/footer.phtml'; ?>
