<?php /** @var \Bluz\View\Layout $this */ ?>
<?php require_once 'partial/header.phtml'; ?>
<?php require_once 'partial/nav-bar.phtml'; ?>
    <div class="container-fluid">
        <div class="row-fluid">
            <ul class="breadcrumb">
                <li>
                    <a href="/" class="bluz-tooltip" data-placement="bottom" data-original-title="Back to homepage">
                        <i class="icon-home"></i>
                        <?=__('Home')?>
                    </a>
                </li>
                <?php if ($this->breadCrumbs()) foreach ($this->breadCrumbs() as $crump):?>
                    <li>
                        <span class="divider">/</span> <?php echo $crump?>
                    </li>
                <?php endforeach;?>
            </ul>
        </div>
        <?php
        /* @var closure $content */
        echo $this->getContent();
        ?>
    </div>
<?php require_once 'partial/footer.phtml'; ?>
