<? require_once 'partial/header.phtml'; ?>
<? require_once 'partial/nav-bar.phtml'; ?>

    <div class="container-fluid">

        <div class="row-fluid">
            <div class="">
                <ul class="breadcrumb">
                    <li>
                        <a href="/">Home</a>
                    </li>
                    <? if ($this->breadcrumps) foreach ($this->breadcrumps as $crump):?>
                        <li>
                            <span class="divider">/</span> <? echo $crump?>
                        </li>
                    <? endforeach;?>
                </ul>
                <?
                /* @var closure $content */
                echo $content;
                ?>
            </div>
        </div>
        <hr />
        <footer>
            <p align="center">&copy; <?=gmdate('Y')?> Bluz Team</p>
            <pre><? print_r(Bluz\Profiler::data()) ?></pre>
        </footer>
    </div>
<? require_once 'partial/footer.phtml'; ?>
