<?php /** @var \Bluz\View\Layout $this */ ?>
<?php require_once 'partial/header.phtml'; ?>
    <div class="container">
        <div class="row">
            <div class="span4 offset4">
                    <?php
                    /* @var closure $content */
                    echo $this->getContent();
                    ?>
            </div>
        </div>
    </div>
<?php require_once 'partial/footer.phtml'; ?>
