<?php /** @var \Bluz\View\Layout $this */ ?>
<?php require_once 'partial/header.phtml'; ?>
<?php /** @var \Bluz\View\Layout $this */ ?>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="brand" href="/"><?=__('Bluz')?></a>
            </div>
        </div>
    </div>
    <div class="container layout-small">
            <div class="center well">
                    <?php
                    /* @var closure $content */
                    echo $this->getContent();
                    ?>
            </div>
    </div>
<?php require_once 'partial/footer.phtml'; ?>
